// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: camera_lens.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CameraLens : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public Header Header { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"c1")]
        public double C1 { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"c2")]
        public double C2 { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"c3")]
        public double C3 { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"f")]
        public double F { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"fun")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Fun { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"scale_to_hfov")]
        public bool ScaleToHfov { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"cutoff_angle")]
        public double CutoffAngle { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"hfov")]
        public double Hfov { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"env_texture_size")]
        public int EnvTextureSize { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
