// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: distortion.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Distortion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public Header Header { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"center")]
        public Vector2d Center { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"k1")]
        public double K1 { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"k2")]
        public double K2 { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"k3")]
        public double K3 { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"p1")]
        public double P1 { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"p2")]
        public double P2 { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
