// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: entity.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Entity : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public Header Header { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public ulong Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
            None = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"LIGHT")]
            Light = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MODEL")]
            Model = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"LINK")]
            Link = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"VISUAL")]
            Visual = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"COLLISION")]
            Collision = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"SENSOR")]
            Sensor = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"JOINT")]
            Joint = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"ACTOR")]
            Actor = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"WORLD")]
            World = 9,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
