// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: imu.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract(Name = @"IMU")]
    public partial class Imu : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public Header Header { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"entity_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EntityName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"orientation")]
        public Quaternion Orientation { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"orientation_covariance")]
        public FloatV OrientationCovariance { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"angular_velocity")]
        public Vector3d AngularVelocity { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"angular_velocity_covariance")]
        public FloatV AngularVelocityCovariance { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"linear_acceleration")]
        public Vector3d LinearAcceleration { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"linear_acceleration_covariance")]
        public FloatV LinearAccelerationCovariance { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
