// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: joint_wrench.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class JointWrench : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body_1_name", IsRequired = true)]
        public string Body1Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"body_1_id", IsRequired = true)]
        public uint Body1Id { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"body_2_name", IsRequired = true)]
        public string Body2Name { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"body_2_id", IsRequired = true)]
        public uint Body2Id { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"body_1_wrench", IsRequired = true)]
        public Wrench Body1Wrench { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"body_2_wrench", IsRequired = true)]
        public Wrench Body2Wrench { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
