// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: laserscan.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LaserScan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public Header Header { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"frame")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Frame { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"world_pose")]
        public Pose WorldPose { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"angle_min")]
        public double AngleMin { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"angle_max")]
        public double AngleMax { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"angle_step")]
        public double AngleStep { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"range_min")]
        public double RangeMin { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"range_max")]
        public double RangeMax { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"count")]
        public uint Count { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"vertical_angle_min")]
        public double VerticalAngleMin { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"vertical_angle_max")]
        public double VerticalAngleMax { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"vertical_angle_step")]
        public double VerticalAngleStep { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"vertical_count")]
        public uint VerticalCount { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"ranges", IsPacked = true)]
        public double[] Ranges { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"intensities", IsPacked = true)]
        public double[] Intensities { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
