// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: lens.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Lens : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"scale_to_hfov")]
        public bool ScaleToHfov { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"c1")]
        public double C1 { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"c2")]
        public double C2 { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"c3")]
        public double C3 { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"focal_length")]
        public double FocalLength { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public FunctionType function_type { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"cutoff_angle")]
        public double CutoffAngle { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"environment_texture_size")]
        public int EnvironmentTextureSize { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"intrinsics_fx")]
        public double IntrinsicsFx { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"intrinsics_fy")]
        public double IntrinsicsFy { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"intrinsics_cx")]
        public double IntrinsicsCx { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"intrinsics_cy")]
        public double IntrinsicsCy { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"intrinsics_skew")]
        public double IntrinsicsSkew { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_NOT_SPECIFIED")]
            TypeNotSpecified = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GNOMONICAL")]
            Gnomonical = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"STEREOGRAPHIC")]
            Stereographic = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"EQUIDISTANT")]
            Equidistant = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"EQUISOLID_ANGLE")]
            EquisolidAngle = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"ORTHOGRAPHIC")]
            Orthographic = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"CUSTOM")]
            Custom = 6,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum FunctionType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"FUNCTION_NOT_SPECIFIED")]
            FunctionNotSpecified = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SIN")]
            Sin = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TAN")]
            Tan = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ID")]
            Id = 3,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
