// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: navsat_with_covariance.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class NavSatWithCovariance : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public Header Header { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"latitude_deg")]
        public double LatitudeDeg { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"longitude_deg")]
        public double LongitudeDeg { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"altitude")]
        public double Altitude { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"position_covariance")]
        public FloatV PositionCovariance { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"position_covariance_type")]
        public uint PositionCovarianceType { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"velocity_east")]
        public double VelocityEast { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"velocity_north")]
        public double VelocityNorth { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"velocity_up")]
        public double VelocityUp { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"velocity_covariance")]
        public FloatV VelocityCovariance { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"velocity_covariance_type")]
        public uint VelocityCovarianceType { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"frame_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string FrameId { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
