// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: raysensor.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RaySensor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public Header Header { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"display_scan")]
        public bool DisplayScan { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"horizontal_samples")]
        public int HorizontalSamples { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"horizontal_resolution")]
        public double HorizontalResolution { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"horizontal_min_angle")]
        public double HorizontalMinAngle { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"horizontal_max_angle")]
        public double HorizontalMaxAngle { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"vertical_samples")]
        public int VerticalSamples { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"vertical_resolution")]
        public double VerticalResolution { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"vertical_min_angle")]
        public double VerticalMinAngle { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"vertical_max_angle")]
        public double VerticalMaxAngle { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"range_min")]
        public double RangeMin { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"range_max")]
        public double RangeMax { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"range_resolution")]
        public double RangeResolution { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
