// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: response.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Response : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"request", IsRequired = true)]
        public string Request { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string response { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Type
        {
            get => __pbn__Type ?? "";
            set => __pbn__Type = value;
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private string __pbn__Type;

        [global::ProtoBuf.ProtoMember(5, Name = @"serialized_data")]
        public byte[] SerializedData
        {
            get => __pbn__SerializedData;
            set => __pbn__SerializedData = value;
        }
        public bool ShouldSerializeSerializedData() => __pbn__SerializedData != null;
        public void ResetSerializedData() => __pbn__SerializedData = null;
        private byte[] __pbn__SerializedData;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
