// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: sensor_noise.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SensorNoise : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public Header Header { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Type type { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"mean")]
        public double Mean { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"stddev")]
        public double Stddev { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"bias_mean")]
        public double BiasMean { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"bias_stddev")]
        public double BiasStddev { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"precision")]
        public double Precision { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"dynamic_bias_stddev")]
        public double DynamicBiasStddev { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"dynamic_bias_correlation_time")]
        public double DynamicBiasCorrelationTime { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
            None = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"GAUSSIAN")]
            Gaussian = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GAUSSIAN_QUANTIZED")]
            GaussianQuantized = 3,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
