// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: world_stats.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WorldStatistics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"header")]
        public Header Header { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"sim_time")]
        public Time SimTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"pause_time")]
        public Time PauseTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"real_time")]
        public Time RealTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"paused")]
        public bool Paused { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"iterations")]
        public ulong Iterations { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"model_count")]
        public int ModelCount { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"log_playback_stats")]
        public LogPlaybackStatistics LogPlaybackStats { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"real_time_factor")]
        public double RealTimeFactor { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"step_size")]
        public Time StepSize { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"stepping")]
        public bool Stepping { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
