// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: world_stats.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WorldStatistics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"sim_time", IsRequired = true)]
        public Time SimTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"pause_time", IsRequired = true)]
        public Time PauseTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"real_time", IsRequired = true)]
        public Time RealTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"paused", IsRequired = true)]
        public bool Paused { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"iterations", IsRequired = true)]
        public ulong Iterations { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"model_count")]
        public int ModelCount
        {
            get => __pbn__ModelCount.GetValueOrDefault();
            set => __pbn__ModelCount = value;
        }
        public bool ShouldSerializeModelCount() => __pbn__ModelCount != null;
        public void ResetModelCount() => __pbn__ModelCount = null;
        private int? __pbn__ModelCount;

        [global::ProtoBuf.ProtoMember(8, Name = @"log_playback_stats")]
        public LogPlaybackStatistics LogPlaybackStats { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
