@ECHO OFF
SETLOCAL EnableDelayedExpansion
SET TargetWorld=
SET HeadlessArgs=
SET CaptureScreen=false

:ParseArgs
IF "%~1" == "" GOTO EndParseArgs
IF /I "%~1" == "-h" (
	ECHO Option --headless was specified!!
	SET HeadlessArgs=-batchmode
) ELSE IF /I "%~1" == "--headless" (
	ECHO Option --headless was specified!!
	SET HeadlessArgs=-batchmode
) ELSE IF /I "%~1" == "-w" (
	IF "%~2" == "" (
		ECHO world file required
		CALL :PrintWorldList
		EXIT /B 1
	)
	ECHO Option --world has value: %~2
	SET TargetWorld=%~2
	SHIFT
) ELSE IF /I "%~1" == "--world" (
	IF "%~2" == "" (
		ECHO world file required
		CALL :PrintWorldList
		EXIT /B 1
	)
	ECHO Option --world has value: %~2
	SET TargetWorld=%~2
	SHIFT
) ELSE IF /I "%~1" == "-c" (
	ECHO Option --capture-screen was specified!!
	SET CaptureScreen=true
) ELSE IF /I "%~1" == "--capture-screen" (
	ECHO Option --capture-screen was specified!!
	SET CaptureScreen=true
) ELSE IF /I "%~1" == "--install-completion" (
	CALL :InstallCompletion
	EXIT /B 0
) ELSE IF "%TargetWorld%" == "" (
	SET TargetWorld=%~1
) ELSE (
	ECHO Unknown option: %~1
	ECHO Possible options: -h^|--headless, -w^|--world, -c^|--capture-screen, --install-completion
	EXIT /B 1
)
SHIFT
GOTO ParseArgs

:EndParseArgs

IF NOT DEFINED CLOISIM_WORLD_PATH (
	ECHO.
	ECHO   'CLOISIM_WORLD_PATH' is empty
	CALL :ShowEnvironmentHelp
) ELSE IF NOT DEFINED CLOISIM_MODEL_PATH (
	ECHO.
	ECHO   'CLOISIM_MODEL_PATH' is empty
	CALL :ShowEnvironmentHelp
) ELSE IF NOT DEFINED CLOISIM_FILES_PATH (
	ECHO.
	ECHO   'CLOISIM_FILES_PATH' is empty
	CALL :ShowEnvironmentHelp
)

ECHO [Environments for CLOiSim]
ECHO  CLOISIM_WORLD_PATH=%CLOISIM_WORLD_PATH%
ECHO  CLOISIM_MODEL_PATH=%CLOISIM_MODEL_PATH%
ECHO  CLOISIM_FILES_PATH=%CLOISIM_FILES_PATH%
ECHO.

IF "%TargetWorld%" == "" (
	ECHO   Pass the world file name as a 1st argument
	ECHO      ex^) run.bat lg_seocho.world
	ECHO.
	ECHO  OR with options
	ECHO      ex^) run.bat --world lg_seocho.world
	ECHO      ex^) run.bat --world empty.world --headless
	ECHO      ex^) run.bat --headless --world empty.world --capture-screen
	ECHO.
	ECHO  Install PowerShell auto-completion ^(one-time^):
	ECHO      run.bat --install-completion
	CALL :PrintWorldList
) ELSE (
	CALL :WorldValidationCheck "!TargetWorld!"
	IF !ERRORLEVEL! NEQ 0 (
		ECHO.
		ECHO  Invalid world file name or World file NOT exist.
		CALL :PrintWorldList
		EXIT /B 1
	)

	SET CaptureArgs=
	IF "!CaptureScreen!" == "true" (
		WHERE ffmpeg >NUL 2>&1
		IF !ERRORLEVEL! NEQ 0 (
			ECHO WARNING: ffmpeg is not installed. Screen capture may not work.
		)
		FOR /F %%T IN ('powershell -NoProfile -Command "Get-Date -Format yyyyMMddHHmmss"') DO SET CAPTURE_TS=%%T
		SET CaptureArgs=-capture simulation_!CAPTURE_TS!
	)

	FOR /F %%T IN ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd_HHmmss"') DO SET LOG_TS=%%T
	SET LOG_FILE=CLOiSim_!LOG_TS!.log

	CLOiSim.exe -logFile "!LOG_FILE!" !HeadlessArgs! -world !TargetWorld! !CaptureArgs!
	SET CLOISIM_EXIT_CODE=!ERRORLEVEL!

	IF !CLOISIM_EXIT_CODE! NEQ 0 (
		CALL :CollectCrashDump !CLOISIM_EXIT_CODE!
	)
)

EXIT /B %ERRORLEVEL%

:CollectCrashDump
	SETLOCAL
	SET EXIT_CODE=%~1
	REM Use PowerShell for locale-independent timestamp
	FOR /F %%I IN ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd_HHmmss"') DO SET TIMESTAMP=%%I
	IF "!TIMESTAMP!"=="" SET TIMESTAMP=unknown
	SET DUMP_DIR=CrashDumps\crash_shell_%TIMESTAMP%

	ECHO.
	ECHO ========================================
	ECHO  CLOiSim exited with code: %EXIT_CODE%
	ECHO  Collecting crash dump...
	ECHO ========================================

	IF NOT EXIST "%DUMP_DIR%" MKDIR "%DUMP_DIR%"

	REM 1. Copy Player.log
	SET LOG_DIR=%APPDATA%\..\LocalLow\LGE.RoboticsPlatform\CLOiSim
	IF EXIST "%LOG_DIR%\Player.log" COPY "%LOG_DIR%\Player.log" "%DUMP_DIR%\Player.log" >NUL
	IF EXIST "%LOG_DIR%\Player-prev.log" COPY "%LOG_DIR%\Player-prev.log" "%DUMP_DIR%\Player-prev.log" >NUL
	IF DEFINED LOG_FILE (
		IF EXIST "%LOG_FILE%" COPY "%LOG_FILE%" "%DUMP_DIR%\CLOiSim_local.log" >NUL
	)

	REM 2. Copy Unity CrashDumps (generated by CrashReporter.cs)
	IF EXIST "CrashDumps" (
		FOR /D %%D IN (CrashDumps\crash_2*) DO (
			IF /I NOT "%%D"=="%DUMP_DIR%" (
				XCOPY "%%D" "%DUMP_DIR%\%%~nxD\" /E /I /Q >NUL 2>&1
			)
		)
	)

	REM 3. Save environment and system info
	(
		ECHO Exit Code         : %EXIT_CODE%
		ECHO Crash Time        : %DATE% %TIME%
		ECHO World File        : %TargetWorld%
		ECHO Headless          : %HeadlessArgs%
		ECHO OS                : %OS%
		ECHO Computer          : %COMPUTERNAME%
		ECHO Processor         : %PROCESSOR_IDENTIFIER%
		ECHO CLOISIM_FILES_PATH: %CLOISIM_FILES_PATH%
		ECHO CLOISIM_MODEL_PATH: %CLOISIM_MODEL_PATH%
		ECHO CLOISIM_WORLD_PATH: %CLOISIM_WORLD_PATH%
	) > "%DUMP_DIR%\env_info.txt"

	REM 4. Package into zip if PowerShell available
	WHERE powershell >NUL 2>&1
	IF !ERRORLEVEL! EQU 0 (
		SET ARCHIVE=CrashDumps\crash_%TIMESTAMP%.zip
		powershell -NoProfile -Command "Compress-Archive -Path '%DUMP_DIR%' -DestinationPath '!ARCHIVE!' -Force"
		ECHO.
		ECHO  Crash dump saved: !ARCHIVE!
	)

	ECHO  Dump directory  : %DUMP_DIR%
	ECHO ========================================
	ENDLOCAL
EXIT /B 0

:InstallCompletion
	WHERE powershell >NUL 2>&1
	IF !ERRORLEVEL! NEQ 0 (
		ECHO PowerShell is required for auto-completion support.
		EXIT /B 1
	)

	powershell -NoProfile -ExecutionPolicy Bypass -Command ^
	"$compDir = Join-Path $env:LOCALAPPDATA 'CLOiSim'; " ^
	"New-Item -ItemType Directory -Force -Path $compDir | Out-Null; " ^
	"$compFile = Join-Path $compDir 'completion.ps1'; " ^
	"@'" ^
	"" ^
	"Register-ArgumentCompleter -Native -CommandName 'run.bat' -ScriptBlock {" ^
	"    param($wordToComplete, $commandAst, $cursorPosition)" ^
	"    $opts = @('--headless', '--world', '--capture-screen', '--install-completion', '-h', '-w', '-c')" ^
	"    $tokens = $commandAst.ToString() -split '\s+'" ^
	"    $prev = if ($tokens.Count -ge 2) { $tokens[-1] } else { '' }" ^
	"    if ($prev -eq '--world' -or $prev -eq '-w') {" ^
	"        $worldPath = $env:CLOISIM_WORLD_PATH" ^
	"        if ($worldPath) {" ^
	"            foreach ($dir in $worldPath -split ';') {" ^
	"                if (Test-Path $dir) {" ^
	"                    Get-ChildItem -Path $dir -Filter '*.world' -File | ForEach-Object {" ^
	"                        [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Name)" ^
	"                    }" ^
	"                }" ^
	"            }" ^
	"        }" ^
	"    } elseif ($wordToComplete.StartsWith('-')) {" ^
	"        $opts | Where-Object { $_ -like \"$wordToComplete*\" } | ForEach-Object {" ^
	"            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterName', $_)" ^
	"        }" ^
	"    } else {" ^
	"        $worldPath = $env:CLOISIM_WORLD_PATH" ^
	"        if ($worldPath) {" ^
	"            foreach ($dir in $worldPath -split ';') {" ^
	"                if (Test-Path $dir) {" ^
	"                    Get-ChildItem -Path $dir -Filter '*.world' -File | ForEach-Object {" ^
	"                        [System.Management.Automation.CompletionResult]::new($_.Name, $_.Name, 'ParameterValue', $_.Name)" ^
	"                    }" ^
	"                }" ^
	"            }" ^
	"        }" ^
	"    }" ^
	"}" ^
	"" ^
	"'@ | Set-Content -Path $compFile -Encoding UTF8; " ^
	"$profileDir = Split-Path $PROFILE -Parent; " ^
	"if (!(Test-Path $profileDir)) { New-Item -ItemType Directory -Force -Path $profileDir | Out-Null }; " ^
	"if (!(Test-Path $PROFILE)) { New-Item -ItemType File -Force -Path $PROFILE | Out-Null }; " ^
	"$sourceLine = \". '$compFile'\"; " ^
	"$content = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue; " ^
	"if (!$content -or !$content.Contains($sourceLine)) { Add-Content -Path $PROFILE -Value \"`n$sourceLine\" }; " ^
	"Write-Host 'PowerShell completion installed to:' $compFile; " ^
	"Write-Host 'Added to PowerShell profile:' $PROFILE; " ^
	"Write-Host 'Open a new PowerShell terminal to enable auto-completion.'"

	ECHO.
	ECHO NOTE: Auto-completion only works in PowerShell, not in cmd.exe.
EXIT /B 0

:ShowEnvironmentHelp
	ECHO.
	ECHO Please set environment path before run the simulation.
	ECHO.
	ECHO   SET CLOISIM_FILES_PATH=C:\Unity\cloisim\materials
	ECHO   SET CLOISIM_MODEL_PATH=C:\Unity\cloisim\resource\models
	ECHO   SET CLOISIM_WORLD_PATH=C:\Unity\cloisim\resource\worlds
	ECHO.
	ECHO Multiple path supports only for 'CLOISIM_MODEL_PATH'
	ECHO   ex^) SET CLOISIM_MODEL_PATH=C:\A\B\models;C:\A\B\models;C:\models
	ECHO.
EXIT /B 0

:PrintWorldList
	ECHO.
	ECHO.
	ECHO ^<Possible all world list in CLOISIM_WORLD_PATH^>
	ECHO.
	IF NOT DEFINED CLOISIM_WORLD_PATH EXIT /B 0
	SET "REMAINING=%CLOISIM_WORLD_PATH%"
:PrintWorldListLoop
	IF "!REMAINING!" == "" EXIT /B 0
	FOR /F "tokens=1* delims=;" %%A IN ("!REMAINING!") DO (
		SET "WORLD_DIR=%%A"
		SET "REMAINING=%%B"
	)
	ECHO [!WORLD_DIR!]
	IF EXIST "!WORLD_DIR!" (
		FOR %%F IN ("!WORLD_DIR!\*.world") DO (
			ECHO  -^> %%~nxF
		)
	)
	IF DEFINED REMAINING GOTO PrintWorldListLoop
EXIT /B 0

:WorldValidationCheck
	SETLOCAL
	SET "CHECK_WORLD=%~1"
	IF NOT DEFINED CLOISIM_WORLD_PATH (
		ENDLOCAL
		EXIT /B 1
	)
	SET "REMAINING=%CLOISIM_WORLD_PATH%"
:WorldValidationLoop
	IF "!REMAINING!" == "" (
		ENDLOCAL
		EXIT /B 1
	)
	FOR /F "tokens=1* delims=;" %%A IN ("!REMAINING!") DO (
		SET "WORLD_DIR=%%A"
		SET "REMAINING=%%B"
	)
	IF EXIST "!WORLD_DIR!\!CHECK_WORLD!" (
		ENDLOCAL
		EXIT /B 0
	)
	GOTO WorldValidationLoop
EXIT /B 0