@ECHO OFF
SETLOCAL EnableDelayedExpansion
SET TargetWorld=
SET HeadlessArgs=

:ParseArgs
IF "%~1" == "" GOTO EndParseArgs
IF /I "%~1" == "-h" (
	SET HeadlessArgs=-batchmode
) ELSE IF /I "%~1" == "--headless" (
	SET HeadlessArgs=-batchmode
) ELSE IF /I "%~1" == "-w" (
	SET TargetWorld=%~2
	SHIFT
) ELSE IF /I "%~1" == "--world" (
	SET TargetWorld=%~2
	SHIFT
) ELSE IF "%TargetWorld%" == "" (
	SET TargetWorld=%~1
)
SHIFT
GOTO ParseArgs

:EndParseArgs

IF NOT DEFINED CLOISIM_WORLD_PATH (
	ECHO.
	ECHO CLOISIM_WORLD_PATH is empty
	CALL :ShowEnvironmentHelp
) ELSE IF NOT DEFINED CLOISIM_MODEL_PATH (
	ECHO.
	ECHO CLOISIM_MODEL_PATH is empty
	CALL :ShowEnvironmentHelp
) ELSE IF NOT DEFINED CLOISIM_FILES_PATH (
	ECHO.
	ECHO CLOISIM_FILES_PATH is empty
	CALL :ShowEnvironmentHelp
) ELSE IF "%TargetWorld%" == "" (
	ECHO.
	ECHO Pass the world file name as a 1st argument
	ECHO.
	ECHO   ex^) run.bat lg_seocho.world
	ECHO   ex^) run.bat --world lg_seocho.world
	ECHO   ex^) run.bat --headless --world lg_seocho.world
	ECHO.
) ELSE (
	ECHO.
	ECHO Environments for CLOiSim
	ECHO   CLOISIM_WORLD_PATH=%CLOISIM_WORLD_PATH%
	ECHO   CLOISIM_MODEL_PATH=%CLOISIM_MODEL_PATH%
	ECHO   CLOISIM_FILES_PATH=%CLOISIM_FILES_PATH%
	ECHO.
	CLOiSim.exe %HeadlessArgs% -world %TargetWorld%
	SET CLOISIM_EXIT_CODE=!ERRORLEVEL!

	IF !CLOISIM_EXIT_CODE! NEQ 0 (
		CALL :CollectCrashDump !CLOISIM_EXIT_CODE!
	)
)

EXIT /B %ERRORLEVEL%

:CollectCrashDump
	SETLOCAL
	SET EXIT_CODE=%~1
	REM Use PowerShell for locale-independent timestamp
	FOR /F %%I IN ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd_HHmmss"') DO SET TIMESTAMP=%%I
	IF "!TIMESTAMP!"=="" SET TIMESTAMP=unknown
	SET DUMP_DIR=CrashDumps\crash_shell_%TIMESTAMP%

	ECHO.
	ECHO ========================================
	ECHO  CLOiSim exited with code: %EXIT_CODE%
	ECHO  Collecting crash dump...
	ECHO ========================================

	IF NOT EXIST "%DUMP_DIR%" MKDIR "%DUMP_DIR%"

	REM 1. Copy Player.log
	SET LOG_DIR=%APPDATA%\..\LocalLow\LGE.RoboticsPlatform\CLOiSim
	IF EXIST "%LOG_DIR%\Player.log" COPY "%LOG_DIR%\Player.log" "%DUMP_DIR%\Player.log" >NUL
	IF EXIST "%LOG_DIR%\Player-prev.log" COPY "%LOG_DIR%\Player-prev.log" "%DUMP_DIR%\Player-prev.log" >NUL

	REM 2. Copy Unity CrashDumps (generated by CrashReporter.cs)
	IF EXIST "CrashDumps" (
		FOR /D %%D IN (CrashDumps\crash_2*) DO (
			IF /I NOT "%%D"=="%DUMP_DIR%" (
				XCOPY "%%D" "%DUMP_DIR%\%%~nxD\" /E /I /Q >NUL 2>&1
			)
		)
	)

	REM 3. Save environment and system info
	(
		ECHO Exit Code         : %EXIT_CODE%
		ECHO Crash Time        : %DATE% %TIME%
		ECHO World File        : %TargetWorld%
		ECHO Headless          : %HeadlessArgs%
		ECHO OS                : %OS%
		ECHO Computer          : %COMPUTERNAME%
		ECHO Processor         : %PROCESSOR_IDENTIFIER%
		ECHO CLOISIM_FILES_PATH: %CLOISIM_FILES_PATH%
		ECHO CLOISIM_MODEL_PATH: %CLOISIM_MODEL_PATH%
		ECHO CLOISIM_WORLD_PATH: %CLOISIM_WORLD_PATH%
	) > "%DUMP_DIR%\env_info.txt"

	REM 4. Package into zip if PowerShell available
	WHERE powershell >NUL 2>&1
	IF !ERRORLEVEL! EQU 0 (
		SET ARCHIVE=CrashDumps\crash_%TIMESTAMP%.zip
		powershell -NoProfile -Command "Compress-Archive -Path '%DUMP_DIR%' -DestinationPath '!ARCHIVE!' -Force"
		ECHO.
		ECHO  Crash dump saved: !ARCHIVE!
	)

	ECHO  Dump directory  : %DUMP_DIR%
	ECHO ========================================
	ENDLOCAL
EXIT /B 0

:ShowEnvironmentHelp
	@ECHO OFF
	ECHO.
	ECHO Please set environment path before run the simulation.
	ECHO.
	ECHO   export CLOISIM_FILES_PATH=/home/Unity/cloisim/materials
	ECHO   export CLOISIM_MODEL_PATH=/home/Unity/cloisim/resource/models
	ECHO   export CLOISIM_WORLD_PATH=/home/Unity/cloisim/resource/worlds
	ECHO.
	ECHO Multiple path supports only for 'CLOSISIM_MODEL_PATH'
	ECHO   ex) export CLOISIM_MODEL_PATH=/A/B/models:/A/B/models:/models
	ECHO.
EXIT /B 0