// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: atmosphere.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Atmosphere : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(Type.Adiabatic)]
        public Type type
        {
            get { return __pbn__type ?? Type.Adiabatic; }
            set { __pbn__type = value; }
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private Type? __pbn__type;

        [global::ProtoBuf.ProtoMember(2, Name = @"temperature")]
        public double Temperature
        {
            get { return __pbn__Temperature.GetValueOrDefault(); }
            set { __pbn__Temperature = value; }
        }
        public bool ShouldSerializeTemperature() => __pbn__Temperature != null;
        public void ResetTemperature() => __pbn__Temperature = null;
        private double? __pbn__Temperature;

        [global::ProtoBuf.ProtoMember(3, Name = @"pressure")]
        public double Pressure
        {
            get { return __pbn__Pressure.GetValueOrDefault(); }
            set { __pbn__Pressure = value; }
        }
        public bool ShouldSerializePressure() => __pbn__Pressure != null;
        public void ResetPressure() => __pbn__Pressure = null;
        private double? __pbn__Pressure;

        [global::ProtoBuf.ProtoMember(4, Name = @"mass_density")]
        public double MassDensity
        {
            get { return __pbn__MassDensity.GetValueOrDefault(); }
            set { __pbn__MassDensity = value; }
        }
        public bool ShouldSerializeMassDensity() => __pbn__MassDensity != null;
        public void ResetMassDensity() => __pbn__MassDensity = null;
        private double? __pbn__MassDensity;

        [global::ProtoBuf.ProtoMember(5, Name = @"enable_atmosphere")]
        public bool EnableAtmosphere
        {
            get { return __pbn__EnableAtmosphere.GetValueOrDefault(); }
            set { __pbn__EnableAtmosphere = value; }
        }
        public bool ShouldSerializeEnableAtmosphere() => __pbn__EnableAtmosphere != null;
        public void ResetEnableAtmosphere() => __pbn__EnableAtmosphere = null;
        private bool? __pbn__EnableAtmosphere;

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ADIABATIC")]
            Adiabatic = 1,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
