// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: axis.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Axis : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"xyz", IsRequired = true)]
        public Vector3d Xyz { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"limit_lower", IsRequired = true)]
        public double LimitLower { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"limit_upper", IsRequired = true)]
        public double LimitUpper { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"limit_effort", IsRequired = true)]
        public double LimitEffort { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"limit_velocity", IsRequired = true)]
        public double LimitVelocity { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"damping", IsRequired = true)]
        public double Damping { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"friction", IsRequired = true)]
        public double Friction { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"use_parent_model_frame", IsRequired = true)]
        public bool UseParentModelFrame { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
