// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: cessna.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Cessna : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"propeller_speed")]
        public float PropellerSpeed
        {
            get { return __pbn__PropellerSpeed.GetValueOrDefault(); }
            set { __pbn__PropellerSpeed = value; }
        }
        public bool ShouldSerializePropellerSpeed() => __pbn__PropellerSpeed != null;
        public void ResetPropellerSpeed() => __pbn__PropellerSpeed = null;
        private float? __pbn__PropellerSpeed;

        [global::ProtoBuf.ProtoMember(2, Name = @"left_aileron")]
        public float LeftAileron
        {
            get { return __pbn__LeftAileron.GetValueOrDefault(); }
            set { __pbn__LeftAileron = value; }
        }
        public bool ShouldSerializeLeftAileron() => __pbn__LeftAileron != null;
        public void ResetLeftAileron() => __pbn__LeftAileron = null;
        private float? __pbn__LeftAileron;

        [global::ProtoBuf.ProtoMember(3, Name = @"left_flap")]
        public float LeftFlap
        {
            get { return __pbn__LeftFlap.GetValueOrDefault(); }
            set { __pbn__LeftFlap = value; }
        }
        public bool ShouldSerializeLeftFlap() => __pbn__LeftFlap != null;
        public void ResetLeftFlap() => __pbn__LeftFlap = null;
        private float? __pbn__LeftFlap;

        [global::ProtoBuf.ProtoMember(4, Name = @"right_aileron")]
        public float RightAileron
        {
            get { return __pbn__RightAileron.GetValueOrDefault(); }
            set { __pbn__RightAileron = value; }
        }
        public bool ShouldSerializeRightAileron() => __pbn__RightAileron != null;
        public void ResetRightAileron() => __pbn__RightAileron = null;
        private float? __pbn__RightAileron;

        [global::ProtoBuf.ProtoMember(5, Name = @"right_flap")]
        public float RightFlap
        {
            get { return __pbn__RightFlap.GetValueOrDefault(); }
            set { __pbn__RightFlap = value; }
        }
        public bool ShouldSerializeRightFlap() => __pbn__RightFlap != null;
        public void ResetRightFlap() => __pbn__RightFlap = null;
        private float? __pbn__RightFlap;

        [global::ProtoBuf.ProtoMember(6, Name = @"elevators")]
        public float Elevators
        {
            get { return __pbn__Elevators.GetValueOrDefault(); }
            set { __pbn__Elevators = value; }
        }
        public bool ShouldSerializeElevators() => __pbn__Elevators != null;
        public void ResetElevators() => __pbn__Elevators = null;
        private float? __pbn__Elevators;

        [global::ProtoBuf.ProtoMember(7, Name = @"rudder")]
        public float Rudder
        {
            get { return __pbn__Rudder.GetValueOrDefault(); }
            set { __pbn__Rudder = value; }
        }
        public bool ShouldSerializeRudder() => __pbn__Rudder != null;
        public void ResetRudder() => __pbn__Rudder = null;
        private float? __pbn__Rudder;

        [global::ProtoBuf.ProtoMember(8, Name = @"cmd_propeller_speed")]
        public float CmdPropellerSpeed
        {
            get { return __pbn__CmdPropellerSpeed.GetValueOrDefault(); }
            set { __pbn__CmdPropellerSpeed = value; }
        }
        public bool ShouldSerializeCmdPropellerSpeed() => __pbn__CmdPropellerSpeed != null;
        public void ResetCmdPropellerSpeed() => __pbn__CmdPropellerSpeed = null;
        private float? __pbn__CmdPropellerSpeed;

        [global::ProtoBuf.ProtoMember(9, Name = @"cmd_left_aileron")]
        public float CmdLeftAileron
        {
            get { return __pbn__CmdLeftAileron.GetValueOrDefault(); }
            set { __pbn__CmdLeftAileron = value; }
        }
        public bool ShouldSerializeCmdLeftAileron() => __pbn__CmdLeftAileron != null;
        public void ResetCmdLeftAileron() => __pbn__CmdLeftAileron = null;
        private float? __pbn__CmdLeftAileron;

        [global::ProtoBuf.ProtoMember(10, Name = @"cmd_left_flap")]
        public float CmdLeftFlap
        {
            get { return __pbn__CmdLeftFlap.GetValueOrDefault(); }
            set { __pbn__CmdLeftFlap = value; }
        }
        public bool ShouldSerializeCmdLeftFlap() => __pbn__CmdLeftFlap != null;
        public void ResetCmdLeftFlap() => __pbn__CmdLeftFlap = null;
        private float? __pbn__CmdLeftFlap;

        [global::ProtoBuf.ProtoMember(11, Name = @"cmd_right_aileron")]
        public float CmdRightAileron
        {
            get { return __pbn__CmdRightAileron.GetValueOrDefault(); }
            set { __pbn__CmdRightAileron = value; }
        }
        public bool ShouldSerializeCmdRightAileron() => __pbn__CmdRightAileron != null;
        public void ResetCmdRightAileron() => __pbn__CmdRightAileron = null;
        private float? __pbn__CmdRightAileron;

        [global::ProtoBuf.ProtoMember(12, Name = @"cmd_right_flap")]
        public float CmdRightFlap
        {
            get { return __pbn__CmdRightFlap.GetValueOrDefault(); }
            set { __pbn__CmdRightFlap = value; }
        }
        public bool ShouldSerializeCmdRightFlap() => __pbn__CmdRightFlap != null;
        public void ResetCmdRightFlap() => __pbn__CmdRightFlap = null;
        private float? __pbn__CmdRightFlap;

        [global::ProtoBuf.ProtoMember(13, Name = @"cmd_elevators")]
        public float CmdElevators
        {
            get { return __pbn__CmdElevators.GetValueOrDefault(); }
            set { __pbn__CmdElevators = value; }
        }
        public bool ShouldSerializeCmdElevators() => __pbn__CmdElevators != null;
        public void ResetCmdElevators() => __pbn__CmdElevators = null;
        private float? __pbn__CmdElevators;

        [global::ProtoBuf.ProtoMember(14, Name = @"cmd_rudder")]
        public float CmdRudder
        {
            get { return __pbn__CmdRudder.GetValueOrDefault(); }
            set { __pbn__CmdRudder = value; }
        }
        public bool ShouldSerializeCmdRudder() => __pbn__CmdRudder != null;
        public void ResetCmdRudder() => __pbn__CmdRudder = null;
        private float? __pbn__CmdRudder;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
