// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: collision.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Collision : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"laser_retro")]
        public double LaserRetro
        {
            get { return __pbn__LaserRetro.GetValueOrDefault(); }
            set { __pbn__LaserRetro = value; }
        }
        public bool ShouldSerializeLaserRetro() => __pbn__LaserRetro != null;
        public void ResetLaserRetro() => __pbn__LaserRetro = null;
        private double? __pbn__LaserRetro;

        [global::ProtoBuf.ProtoMember(4, Name = @"max_contacts")]
        public double MaxContacts
        {
            get { return __pbn__MaxContacts.GetValueOrDefault(); }
            set { __pbn__MaxContacts = value; }
        }
        public bool ShouldSerializeMaxContacts() => __pbn__MaxContacts != null;
        public void ResetMaxContacts() => __pbn__MaxContacts = null;
        private double? __pbn__MaxContacts;

        [global::ProtoBuf.ProtoMember(5, Name = @"pose")]
        public Pose Pose { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"geometry")]
        public Geometry Geometry { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"surface")]
        public Surface Surface { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"visual")]
        public global::System.Collections.Generic.List<Visual> Visuals { get; } = new global::System.Collections.Generic.List<Visual>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
