// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: contact.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Contact : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"collision1", IsRequired = true)]
        public string Collision1 { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"collision2", IsRequired = true)]
        public string Collision2 { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"position")]
        public global::System.Collections.Generic.List<Vector3d> Positions { get; } = new global::System.Collections.Generic.List<Vector3d>();

        [global::ProtoBuf.ProtoMember(4, Name = @"normal")]
        public global::System.Collections.Generic.List<Vector3d> Normals { get; } = new global::System.Collections.Generic.List<Vector3d>();

        [global::ProtoBuf.ProtoMember(5, Name = @"depth")]
        public double[] Depths { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"wrench")]
        public global::System.Collections.Generic.List<JointWrench> Wrenchs { get; } = new global::System.Collections.Generic.List<JointWrench>();

        [global::ProtoBuf.ProtoMember(7, Name = @"time", IsRequired = true)]
        public Time Time { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"world", IsRequired = true)]
        public string World { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
