// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: diagnostics.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Diagnostics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time")]
        public global::System.Collections.Generic.List<DiagTime> Times { get; } = new global::System.Collections.Generic.List<DiagTime>();

        [global::ProtoBuf.ProtoMember(2, Name = @"real_time", IsRequired = true)]
        public Time RealTime { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"sim_time", IsRequired = true)]
        public Time SimTime { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"real_time_factor", IsRequired = true)]
        public double RealTimeFactor { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class DiagTime : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
            public string Name { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"elapsed", IsRequired = true)]
            public Time Elapsed { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"wall", IsRequired = true)]
            public Time Wall { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
