// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: distortion.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Distortion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"center")]
        public Vector2d Center { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"k1")]
        public double K1
        {
            get => __pbn__K1.GetValueOrDefault();
            set => __pbn__K1 = value;
        }
        public bool ShouldSerializeK1() => __pbn__K1 != null;
        public void ResetK1() => __pbn__K1 = null;
        private double? __pbn__K1;

        [global::ProtoBuf.ProtoMember(3, Name = @"k2")]
        public double K2
        {
            get => __pbn__K2.GetValueOrDefault();
            set => __pbn__K2 = value;
        }
        public bool ShouldSerializeK2() => __pbn__K2 != null;
        public void ResetK2() => __pbn__K2 = null;
        private double? __pbn__K2;

        [global::ProtoBuf.ProtoMember(4, Name = @"k3")]
        public double K3
        {
            get => __pbn__K3.GetValueOrDefault();
            set => __pbn__K3 = value;
        }
        public bool ShouldSerializeK3() => __pbn__K3 != null;
        public void ResetK3() => __pbn__K3 = null;
        private double? __pbn__K3;

        [global::ProtoBuf.ProtoMember(5, Name = @"p1")]
        public double P1
        {
            get => __pbn__P1.GetValueOrDefault();
            set => __pbn__P1 = value;
        }
        public bool ShouldSerializeP1() => __pbn__P1 != null;
        public void ResetP1() => __pbn__P1 = null;
        private double? __pbn__P1;

        [global::ProtoBuf.ProtoMember(6, Name = @"p2")]
        public double P2
        {
            get => __pbn__P2.GetValueOrDefault();
            set => __pbn__P2 = value;
        }
        public bool ShouldSerializeP2() => __pbn__P2 != null;
        public void ResetP2() => __pbn__P2 = null;
        private double? __pbn__P2;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
