// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: factory.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Factory : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"sdf")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Sdf
        {
            get { return __pbn__Sdf ?? ""; }
            set { __pbn__Sdf = value; }
        }
        public bool ShouldSerializeSdf() => __pbn__Sdf != null;
        public void ResetSdf() => __pbn__Sdf = null;
        private string __pbn__Sdf;

        [global::ProtoBuf.ProtoMember(2, Name = @"sdf_filename")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SdfFilename
        {
            get { return __pbn__SdfFilename ?? ""; }
            set { __pbn__SdfFilename = value; }
        }
        public bool ShouldSerializeSdfFilename() => __pbn__SdfFilename != null;
        public void ResetSdfFilename() => __pbn__SdfFilename = null;
        private string __pbn__SdfFilename;

        [global::ProtoBuf.ProtoMember(3, Name = @"pose")]
        public Pose Pose { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"edit_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EditName
        {
            get { return __pbn__EditName ?? ""; }
            set { __pbn__EditName = value; }
        }
        public bool ShouldSerializeEditName() => __pbn__EditName != null;
        public void ResetEditName() => __pbn__EditName = null;
        private string __pbn__EditName;

        [global::ProtoBuf.ProtoMember(5, Name = @"clone_model_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CloneModelName
        {
            get { return __pbn__CloneModelName ?? ""; }
            set { __pbn__CloneModelName = value; }
        }
        public bool ShouldSerializeCloneModelName() => __pbn__CloneModelName != null;
        public void ResetCloneModelName() => __pbn__CloneModelName = null;
        private string __pbn__CloneModelName;

        [global::ProtoBuf.ProtoMember(6, Name = @"allow_renaming")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool AllowRenaming
        {
            get { return __pbn__AllowRenaming ?? true; }
            set { __pbn__AllowRenaming = value; }
        }
        public bool ShouldSerializeAllowRenaming() => __pbn__AllowRenaming != null;
        public void ResetAllowRenaming() => __pbn__AllowRenaming = null;
        private bool? __pbn__AllowRenaming;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
