// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: fog.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Fog : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(FogType.None)]
        public FogType Type
        {
            get { return __pbn__Type ?? FogType.None; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private FogType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(2, Name = @"color")]
        public Color Color { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"density")]
        public float Density
        {
            get { return __pbn__Density.GetValueOrDefault(); }
            set { __pbn__Density = value; }
        }
        public bool ShouldSerializeDensity() => __pbn__Density != null;
        public void ResetDensity() => __pbn__Density = null;
        private float? __pbn__Density;

        [global::ProtoBuf.ProtoMember(4, Name = @"start")]
        public float Start
        {
            get { return __pbn__Start.GetValueOrDefault(); }
            set { __pbn__Start = value; }
        }
        public bool ShouldSerializeStart() => __pbn__Start != null;
        public void ResetStart() => __pbn__Start = null;
        private float? __pbn__Start;

        [global::ProtoBuf.ProtoMember(5, Name = @"end")]
        public float End
        {
            get { return __pbn__End.GetValueOrDefault(); }
            set { __pbn__End = value; }
        }
        public bool ShouldSerializeEnd() => __pbn__End != null;
        public void ResetEnd() => __pbn__End = null;
        private float? __pbn__End;

        [global::ProtoBuf.ProtoContract()]
        public enum FogType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
            None = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"LINEAR")]
            Linear = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"EXPONENTIAL")]
            Exponential = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"EXPONENTIAL2")]
            Exponential2 = 4,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
