// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: geometry.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Geometry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(Type.Box)]
        public Type type
        {
            get { return __pbn__type ?? Type.Box; }
            set { __pbn__type = value; }
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private Type? __pbn__type;

        [global::ProtoBuf.ProtoMember(2, Name = @"box")]
        public BoxGeom Box { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"cylinder")]
        public CylinderGeom Cylinder { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"plane")]
        public PlaneGeom Plane { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"sphere")]
        public SphereGeom Sphere { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"image")]
        public ImageGeom Image { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"heightmap")]
        public HeightmapGeom Heightmap { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"mesh")]
        public MeshGeom Mesh { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"points")]
        public global::System.Collections.Generic.List<Vector3d> Points { get; } = new global::System.Collections.Generic.List<Vector3d>();

        [global::ProtoBuf.ProtoMember(10, Name = @"polyline")]
        public global::System.Collections.Generic.List<Polyline> Polylines { get; } = new global::System.Collections.Generic.List<Polyline>();

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"BOX")]
            Box = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"CYLINDER")]
            Cylinder = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SPHERE")]
            Sphere = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"PLANE")]
            Plane = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"IMAGE")]
            Image = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"HEIGHTMAP")]
            Heightmap = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"MESH")]
            Mesh = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"TRIANGLE_FAN")]
            TriangleFan = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"LINE_STRIP")]
            LineStrip = 9,
            [global::ProtoBuf.ProtoEnum(Name = @"POLYLINE")]
            Polyline = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"EMPTY")]
            Empty = 11,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
