// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: gps.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract(Name = @"GPS")]
    public partial class Gps : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time", IsRequired = true)]
        public Time Time { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"link_name", IsRequired = true)]
        public string LinkName { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"latitude_deg", IsRequired = true)]
        public double LatitudeDeg { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"longitude_deg", IsRequired = true)]
        public double LongitudeDeg { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"altitude", IsRequired = true)]
        public double Altitude { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"velocity_east")]
        public double VelocityEast
        {
            get { return __pbn__VelocityEast.GetValueOrDefault(); }
            set { __pbn__VelocityEast = value; }
        }
        public bool ShouldSerializeVelocityEast() => __pbn__VelocityEast != null;
        public void ResetVelocityEast() => __pbn__VelocityEast = null;
        private double? __pbn__VelocityEast;

        [global::ProtoBuf.ProtoMember(7, Name = @"velocity_north")]
        public double VelocityNorth
        {
            get { return __pbn__VelocityNorth.GetValueOrDefault(); }
            set { __pbn__VelocityNorth = value; }
        }
        public bool ShouldSerializeVelocityNorth() => __pbn__VelocityNorth != null;
        public void ResetVelocityNorth() => __pbn__VelocityNorth = null;
        private double? __pbn__VelocityNorth;

        [global::ProtoBuf.ProtoMember(8, Name = @"velocity_up")]
        public double VelocityUp
        {
            get { return __pbn__VelocityUp.GetValueOrDefault(); }
            set { __pbn__VelocityUp = value; }
        }
        public bool ShouldSerializeVelocityUp() => __pbn__VelocityUp != null;
        public void ResetVelocityUp() => __pbn__VelocityUp = null;
        private double? __pbn__VelocityUp;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
