// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: heightmapgeom.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class HeightmapGeom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"image")]
        public Image Image { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"size", IsRequired = true)]
        public Vector3d Size { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"origin")]
        public Vector3d Origin { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"heights")]
        public float[] Heights { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"width")]
        public int Width
        {
            get { return __pbn__Width.GetValueOrDefault(); }
            set { __pbn__Width = value; }
        }
        public bool ShouldSerializeWidth() => __pbn__Width != null;
        public void ResetWidth() => __pbn__Width = null;
        private int? __pbn__Width;

        [global::ProtoBuf.ProtoMember(6, Name = @"height")]
        public int Height
        {
            get { return __pbn__Height.GetValueOrDefault(); }
            set { __pbn__Height = value; }
        }
        public bool ShouldSerializeHeight() => __pbn__Height != null;
        public void ResetHeight() => __pbn__Height = null;
        private int? __pbn__Height;

        [global::ProtoBuf.ProtoMember(7, Name = @"texture")]
        public global::System.Collections.Generic.List<Texture> Textures { get; } = new global::System.Collections.Generic.List<Texture>();

        [global::ProtoBuf.ProtoMember(8, Name = @"blend")]
        public global::System.Collections.Generic.List<Blend> Blends { get; } = new global::System.Collections.Generic.List<Blend>();

        [global::ProtoBuf.ProtoMember(9, Name = @"use_terrain_paging")]
        public bool UseTerrainPaging
        {
            get { return __pbn__UseTerrainPaging.GetValueOrDefault(); }
            set { __pbn__UseTerrainPaging = value; }
        }
        public bool ShouldSerializeUseTerrainPaging() => __pbn__UseTerrainPaging != null;
        public void ResetUseTerrainPaging() => __pbn__UseTerrainPaging = null;
        private bool? __pbn__UseTerrainPaging;

        [global::ProtoBuf.ProtoMember(10, Name = @"filename")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Filename
        {
            get { return __pbn__Filename ?? ""; }
            set { __pbn__Filename = value; }
        }
        public bool ShouldSerializeFilename() => __pbn__Filename != null;
        public void ResetFilename() => __pbn__Filename = null;
        private string __pbn__Filename;

        [global::ProtoBuf.ProtoMember(11, Name = @"sampling")]
        public uint Sampling
        {
            get { return __pbn__Sampling.GetValueOrDefault(); }
            set { __pbn__Sampling = value; }
        }
        public bool ShouldSerializeSampling() => __pbn__Sampling != null;
        public void ResetSampling() => __pbn__Sampling = null;
        private uint? __pbn__Sampling;

        [global::ProtoBuf.ProtoContract()]
        public partial class Texture : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"diffuse", IsRequired = true)]
            public string Diffuse { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"normal", IsRequired = true)]
            public string Normal { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"size", IsRequired = true)]
            public double Size { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Blend : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"min_height", IsRequired = true)]
            public double MinHeight { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"fade_dist", IsRequired = true)]
            public double FadeDist { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
