// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hydra.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Hydra : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"right", IsRequired = true)]
        public Paddle Right { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"left", IsRequired = true)]
        public Paddle Left { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Paddle : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"pose", IsRequired = true)]
            public Pose Pose { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"button_bumper", IsRequired = true)]
            public bool ButtonBumper { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"button_1", IsRequired = true)]
            public bool Button1 { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"button_2", IsRequired = true)]
            public bool Button2 { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"button_3", IsRequired = true)]
            public bool Button3 { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"button_4", IsRequired = true)]
            public bool Button4 { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"button_joy", IsRequired = true)]
            public bool ButtonJoy { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"button_center", IsRequired = true)]
            public bool ButtonCenter { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"joy_x", IsRequired = true)]
            public double JoyX { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"joy_y", IsRequired = true)]
            public double JoyY { get; set; }

            [global::ProtoBuf.ProtoMember(11, Name = @"trigger", IsRequired = true)]
            public double Trigger { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
