// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: imagegeom.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ImageGeom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uri", IsRequired = true)]
        public string Uri { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"scale")]
        public double Scale
        {
            get { return __pbn__Scale.GetValueOrDefault(); }
            set { __pbn__Scale = value; }
        }
        public bool ShouldSerializeScale() => __pbn__Scale != null;
        public void ResetScale() => __pbn__Scale = null;
        private double? __pbn__Scale;

        [global::ProtoBuf.ProtoMember(3, Name = @"threshold")]
        [global::System.ComponentModel.DefaultValue(255)]
        public int Threshold
        {
            get { return __pbn__Threshold ?? 255; }
            set { __pbn__Threshold = value; }
        }
        public bool ShouldSerializeThreshold() => __pbn__Threshold != null;
        public void ResetThreshold() => __pbn__Threshold = null;
        private int? __pbn__Threshold;

        [global::ProtoBuf.ProtoMember(4, Name = @"height")]
        public double Height
        {
            get { return __pbn__Height.GetValueOrDefault(); }
            set { __pbn__Height = value; }
        }
        public bool ShouldSerializeHeight() => __pbn__Height != null;
        public void ResetHeight() => __pbn__Height = null;
        private double? __pbn__Height;

        [global::ProtoBuf.ProtoMember(5, Name = @"granularity")]
        public int Granularity
        {
            get { return __pbn__Granularity.GetValueOrDefault(); }
            set { __pbn__Granularity = value; }
        }
        public bool ShouldSerializeGranularity() => __pbn__Granularity != null;
        public void ResetGranularity() => __pbn__Granularity = null;
        private int? __pbn__Granularity;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
