// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: imu.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract(Name = @"IMU")]
    public partial class Imu : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stamp", IsRequired = true)]
        public Time Stamp { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"entity_name", IsRequired = true)]
        public string EntityName { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"orientation", IsRequired = true)]
        public Quaternion Orientation { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"angular_velocity", IsRequired = true)]
        public Vector3d AngularVelocity { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"linear_acceleration", IsRequired = true)]
        public Vector3d LinearAcceleration { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
