// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: inertial.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Inertial : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"mass")]
        public double Mass
        {
            get { return __pbn__Mass.GetValueOrDefault(); }
            set { __pbn__Mass = value; }
        }
        public bool ShouldSerializeMass() => __pbn__Mass != null;
        public void ResetMass() => __pbn__Mass = null;
        private double? __pbn__Mass;

        [global::ProtoBuf.ProtoMember(2, Name = @"pose")]
        public Pose Pose { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ixx")]
        public double Ixx
        {
            get { return __pbn__Ixx.GetValueOrDefault(); }
            set { __pbn__Ixx = value; }
        }
        public bool ShouldSerializeIxx() => __pbn__Ixx != null;
        public void ResetIxx() => __pbn__Ixx = null;
        private double? __pbn__Ixx;

        [global::ProtoBuf.ProtoMember(4, Name = @"ixy")]
        public double Ixy
        {
            get { return __pbn__Ixy.GetValueOrDefault(); }
            set { __pbn__Ixy = value; }
        }
        public bool ShouldSerializeIxy() => __pbn__Ixy != null;
        public void ResetIxy() => __pbn__Ixy = null;
        private double? __pbn__Ixy;

        [global::ProtoBuf.ProtoMember(5, Name = @"ixz")]
        public double Ixz
        {
            get { return __pbn__Ixz.GetValueOrDefault(); }
            set { __pbn__Ixz = value; }
        }
        public bool ShouldSerializeIxz() => __pbn__Ixz != null;
        public void ResetIxz() => __pbn__Ixz = null;
        private double? __pbn__Ixz;

        [global::ProtoBuf.ProtoMember(6, Name = @"iyy")]
        public double Iyy
        {
            get { return __pbn__Iyy.GetValueOrDefault(); }
            set { __pbn__Iyy = value; }
        }
        public bool ShouldSerializeIyy() => __pbn__Iyy != null;
        public void ResetIyy() => __pbn__Iyy = null;
        private double? __pbn__Iyy;

        [global::ProtoBuf.ProtoMember(7, Name = @"iyz")]
        public double Iyz
        {
            get { return __pbn__Iyz.GetValueOrDefault(); }
            set { __pbn__Iyz = value; }
        }
        public bool ShouldSerializeIyz() => __pbn__Iyz != null;
        public void ResetIyz() => __pbn__Iyz = null;
        private double? __pbn__Iyz;

        [global::ProtoBuf.ProtoMember(8, Name = @"izz")]
        public double Izz
        {
            get { return __pbn__Izz.GetValueOrDefault(); }
            set { __pbn__Izz = value; }
        }
        public bool ShouldSerializeIzz() => __pbn__Izz != null;
        public void ResetIzz() => __pbn__Izz = null;
        private double? __pbn__Izz;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
