// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: joint.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Joint : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"angle")]
        public double[] Angles { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(Type.Revolute)]
        public Type type
        {
            get { return __pbn__type ?? Type.Revolute; }
            set { __pbn__type = value; }
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private Type? __pbn__type;

        [global::ProtoBuf.ProtoMember(5, Name = @"parent")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Parent
        {
            get { return __pbn__Parent ?? ""; }
            set { __pbn__Parent = value; }
        }
        public bool ShouldSerializeParent() => __pbn__Parent != null;
        public void ResetParent() => __pbn__Parent = null;
        private string __pbn__Parent;

        [global::ProtoBuf.ProtoMember(6, Name = @"parent_id")]
        public uint ParentId
        {
            get { return __pbn__ParentId.GetValueOrDefault(); }
            set { __pbn__ParentId = value; }
        }
        public bool ShouldSerializeParentId() => __pbn__ParentId != null;
        public void ResetParentId() => __pbn__ParentId = null;
        private uint? __pbn__ParentId;

        [global::ProtoBuf.ProtoMember(7, Name = @"child")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Child
        {
            get { return __pbn__Child ?? ""; }
            set { __pbn__Child = value; }
        }
        public bool ShouldSerializeChild() => __pbn__Child != null;
        public void ResetChild() => __pbn__Child = null;
        private string __pbn__Child;

        [global::ProtoBuf.ProtoMember(8, Name = @"child_id")]
        public uint ChildId
        {
            get { return __pbn__ChildId.GetValueOrDefault(); }
            set { __pbn__ChildId = value; }
        }
        public bool ShouldSerializeChildId() => __pbn__ChildId != null;
        public void ResetChildId() => __pbn__ChildId = null;
        private uint? __pbn__ChildId;

        [global::ProtoBuf.ProtoMember(9, Name = @"pose")]
        public Pose Pose { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"axis1")]
        public Axis Axis1 { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"axis2")]
        public Axis Axis2 { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"cfm")]
        public double Cfm
        {
            get { return __pbn__Cfm.GetValueOrDefault(); }
            set { __pbn__Cfm = value; }
        }
        public bool ShouldSerializeCfm() => __pbn__Cfm != null;
        public void ResetCfm() => __pbn__Cfm = null;
        private double? __pbn__Cfm;

        [global::ProtoBuf.ProtoMember(13, Name = @"bounce")]
        public double Bounce
        {
            get { return __pbn__Bounce.GetValueOrDefault(); }
            set { __pbn__Bounce = value; }
        }
        public bool ShouldSerializeBounce() => __pbn__Bounce != null;
        public void ResetBounce() => __pbn__Bounce = null;
        private double? __pbn__Bounce;

        [global::ProtoBuf.ProtoMember(14, Name = @"velocity")]
        public double Velocity
        {
            get { return __pbn__Velocity.GetValueOrDefault(); }
            set { __pbn__Velocity = value; }
        }
        public bool ShouldSerializeVelocity() => __pbn__Velocity != null;
        public void ResetVelocity() => __pbn__Velocity = null;
        private double? __pbn__Velocity;

        [global::ProtoBuf.ProtoMember(15, Name = @"fudge_factor")]
        public double FudgeFactor
        {
            get { return __pbn__FudgeFactor.GetValueOrDefault(); }
            set { __pbn__FudgeFactor = value; }
        }
        public bool ShouldSerializeFudgeFactor() => __pbn__FudgeFactor != null;
        public void ResetFudgeFactor() => __pbn__FudgeFactor = null;
        private double? __pbn__FudgeFactor;

        [global::ProtoBuf.ProtoMember(16, Name = @"limit_cfm")]
        public double LimitCfm
        {
            get { return __pbn__LimitCfm.GetValueOrDefault(); }
            set { __pbn__LimitCfm = value; }
        }
        public bool ShouldSerializeLimitCfm() => __pbn__LimitCfm != null;
        public void ResetLimitCfm() => __pbn__LimitCfm = null;
        private double? __pbn__LimitCfm;

        [global::ProtoBuf.ProtoMember(17, Name = @"limit_erp")]
        public double LimitErp
        {
            get { return __pbn__LimitErp.GetValueOrDefault(); }
            set { __pbn__LimitErp = value; }
        }
        public bool ShouldSerializeLimitErp() => __pbn__LimitErp != null;
        public void ResetLimitErp() => __pbn__LimitErp = null;
        private double? __pbn__LimitErp;

        [global::ProtoBuf.ProtoMember(18, Name = @"suspension_cfm")]
        public double SuspensionCfm
        {
            get { return __pbn__SuspensionCfm.GetValueOrDefault(); }
            set { __pbn__SuspensionCfm = value; }
        }
        public bool ShouldSerializeSuspensionCfm() => __pbn__SuspensionCfm != null;
        public void ResetSuspensionCfm() => __pbn__SuspensionCfm = null;
        private double? __pbn__SuspensionCfm;

        [global::ProtoBuf.ProtoMember(19, Name = @"suspension_erp")]
        public double SuspensionErp
        {
            get { return __pbn__SuspensionErp.GetValueOrDefault(); }
            set { __pbn__SuspensionErp = value; }
        }
        public bool ShouldSerializeSuspensionErp() => __pbn__SuspensionErp != null;
        public void ResetSuspensionErp() => __pbn__SuspensionErp = null;
        private double? __pbn__SuspensionErp;

        [global::ProtoBuf.ProtoMember(20)]
        public Gearbox gearbox { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public Screw screw { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"sensor")]
        public global::System.Collections.Generic.List<Sensor> Sensors { get; } = new global::System.Collections.Generic.List<Sensor>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Gearbox : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"gearbox_reference_body", IsRequired = true)]
            public string GearboxReferenceBody { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"gearbox_ratio", IsRequired = true)]
            public double GearboxRatio { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Screw : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"thread_pitch", IsRequired = true)]
            public double ThreadPitch { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"REVOLUTE")]
            Revolute = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"REVOLUTE2")]
            Revolute2 = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"PRISMATIC")]
            Prismatic = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"UNIVERSAL")]
            Universal = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"BALL")]
            Ball = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"SCREW")]
            Screw = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"GEARBOX")]
            Gearbox = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"FIXED")]
            Fixed = 8,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
