// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: joint_cmd.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class JointCmd : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"axis")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int Axis
        {
            get { return __pbn__Axis ?? 0; }
            set { __pbn__Axis = value; }
        }
        public bool ShouldSerializeAxis() => __pbn__Axis != null;
        public void ResetAxis() => __pbn__Axis = null;
        private int? __pbn__Axis;

        [global::ProtoBuf.ProtoMember(3, Name = @"force")]
        public double Force
        {
            get { return __pbn__Force.GetValueOrDefault(); }
            set { __pbn__Force = value; }
        }
        public bool ShouldSerializeForce() => __pbn__Force != null;
        public void ResetForce() => __pbn__Force = null;
        private double? __pbn__Force;

        [global::ProtoBuf.ProtoMember(4, Name = @"position")]
        public Pid Position { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"velocity")]
        public Pid Velocity { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"reset")]
        public bool Reset
        {
            get { return __pbn__Reset.GetValueOrDefault(); }
            set { __pbn__Reset = value; }
        }
        public bool ShouldSerializeReset() => __pbn__Reset != null;
        public void ResetReset() => __pbn__Reset = null;
        private bool? __pbn__Reset;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
