// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: link.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Link : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"self_collide")]
        public bool SelfCollide
        {
            get { return __pbn__SelfCollide.GetValueOrDefault(); }
            set { __pbn__SelfCollide = value; }
        }
        public bool ShouldSerializeSelfCollide() => __pbn__SelfCollide != null;
        public void ResetSelfCollide() => __pbn__SelfCollide = null;
        private bool? __pbn__SelfCollide;

        [global::ProtoBuf.ProtoMember(4, Name = @"gravity")]
        public bool Gravity
        {
            get { return __pbn__Gravity.GetValueOrDefault(); }
            set { __pbn__Gravity = value; }
        }
        public bool ShouldSerializeGravity() => __pbn__Gravity != null;
        public void ResetGravity() => __pbn__Gravity = null;
        private bool? __pbn__Gravity;

        [global::ProtoBuf.ProtoMember(5, Name = @"kinematic")]
        public bool Kinematic
        {
            get { return __pbn__Kinematic.GetValueOrDefault(); }
            set { __pbn__Kinematic = value; }
        }
        public bool ShouldSerializeKinematic() => __pbn__Kinematic != null;
        public void ResetKinematic() => __pbn__Kinematic = null;
        private bool? __pbn__Kinematic;

        [global::ProtoBuf.ProtoMember(6, Name = @"enabled")]
        public bool Enabled
        {
            get { return __pbn__Enabled.GetValueOrDefault(); }
            set { __pbn__Enabled = value; }
        }
        public bool ShouldSerializeEnabled() => __pbn__Enabled != null;
        public void ResetEnabled() => __pbn__Enabled = null;
        private bool? __pbn__Enabled;

        [global::ProtoBuf.ProtoMember(7, Name = @"density")]
        public Density Density { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"inertial")]
        public Inertial Inertial { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"pose")]
        public Pose Pose { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"visual")]
        public global::System.Collections.Generic.List<Visual> Visuals { get; } = new global::System.Collections.Generic.List<Visual>();

        [global::ProtoBuf.ProtoMember(11, Name = @"collision")]
        public global::System.Collections.Generic.List<Collision> Collisions { get; } = new global::System.Collections.Generic.List<Collision>();

        [global::ProtoBuf.ProtoMember(12, Name = @"sensor")]
        public global::System.Collections.Generic.List<Sensor> Sensors { get; } = new global::System.Collections.Generic.List<Sensor>();

        [global::ProtoBuf.ProtoMember(13, Name = @"projector")]
        public global::System.Collections.Generic.List<Projector> Projectors { get; } = new global::System.Collections.Generic.List<Projector>();

        [global::ProtoBuf.ProtoMember(14, Name = @"canonical")]
        public bool Canonical
        {
            get { return __pbn__Canonical.GetValueOrDefault(); }
            set { __pbn__Canonical = value; }
        }
        public bool ShouldSerializeCanonical() => __pbn__Canonical != null;
        public void ResetCanonical() => __pbn__Canonical = null;
        private bool? __pbn__Canonical;

        [global::ProtoBuf.ProtoMember(15, Name = @"battery")]
        public global::System.Collections.Generic.List<Battery> Batteries { get; } = new global::System.Collections.Generic.List<Battery>();

        [global::ProtoBuf.ProtoMember(16, Name = @"enable_wind")]
        public bool EnableWind
        {
            get { return __pbn__EnableWind.GetValueOrDefault(); }
            set { __pbn__EnableWind = value; }
        }
        public bool ShouldSerializeEnableWind() => __pbn__EnableWind != null;
        public void ResetEnableWind() => __pbn__EnableWind = null;
        private bool? __pbn__EnableWind;

        [global::ProtoBuf.ProtoMember(17, Name = @"wind")]
        public Vector3d Wind { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"light")]
        public global::System.Collections.Generic.List<Light> Lights { get; } = new global::System.Collections.Generic.List<Light>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
