// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: log_control.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LogControl : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start")]
        public bool Start
        {
            get { return __pbn__Start.GetValueOrDefault(); }
            set { __pbn__Start = value; }
        }
        public bool ShouldSerializeStart() => __pbn__Start != null;
        public void ResetStart() => __pbn__Start = null;
        private bool? __pbn__Start;

        [global::ProtoBuf.ProtoMember(2, Name = @"stop")]
        public bool Stop
        {
            get { return __pbn__Stop.GetValueOrDefault(); }
            set { __pbn__Stop = value; }
        }
        public bool ShouldSerializeStop() => __pbn__Stop != null;
        public void ResetStop() => __pbn__Stop = null;
        private bool? __pbn__Stop;

        [global::ProtoBuf.ProtoMember(3, Name = @"paused")]
        public bool Paused
        {
            get { return __pbn__Paused.GetValueOrDefault(); }
            set { __pbn__Paused = value; }
        }
        public bool ShouldSerializePaused() => __pbn__Paused != null;
        public void ResetPaused() => __pbn__Paused = null;
        private bool? __pbn__Paused;

        [global::ProtoBuf.ProtoMember(4, Name = @"base_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string BasePath
        {
            get { return __pbn__BasePath ?? ""; }
            set { __pbn__BasePath = value; }
        }
        public bool ShouldSerializeBasePath() => __pbn__BasePath != null;
        public void ResetBasePath() => __pbn__BasePath = null;
        private string __pbn__BasePath;

        [global::ProtoBuf.ProtoMember(5, Name = @"encoding")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Encoding
        {
            get { return __pbn__Encoding ?? ""; }
            set { __pbn__Encoding = value; }
        }
        public bool ShouldSerializeEncoding() => __pbn__Encoding != null;
        public void ResetEncoding() => __pbn__Encoding = null;
        private string __pbn__Encoding;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
