// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: meshgeom.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MeshGeom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"filename", IsRequired = true)]
        public string Filename { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"scale")]
        public Vector3d Scale { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"submesh")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Submesh
        {
            get { return __pbn__Submesh ?? ""; }
            set { __pbn__Submesh = value; }
        }
        public bool ShouldSerializeSubmesh() => __pbn__Submesh != null;
        public void ResetSubmesh() => __pbn__Submesh = null;
        private string __pbn__Submesh;

        [global::ProtoBuf.ProtoMember(4, Name = @"center_submesh")]
        public bool CenterSubmesh
        {
            get { return __pbn__CenterSubmesh.GetValueOrDefault(); }
            set { __pbn__CenterSubmesh = value; }
        }
        public bool ShouldSerializeCenterSubmesh() => __pbn__CenterSubmesh != null;
        public void ResetCenterSubmesh() => __pbn__CenterSubmesh = null;
        private bool? __pbn__CenterSubmesh;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
