// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: micom_l9s.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract(Name = @"Micom_L9S")]
    public partial class MicomL9S : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"stBmsData_eLevel", IsRequired = true)]
        public int stBmsDataeLevel { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"stBmsData_eStatus", IsRequired = true)]
        public int stBmsDataeStatus { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"stBmsData_eErrorStatus", IsRequired = true)]
        public int stBmsDataeErrorStatus { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"stBmsData_chargerContact", IsRequired = true)]
        public bool stBmsDatachargerContact { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"stDeltaDR_fXmm", IsRequired = true)]
        public float stDeltaDRfXmm { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"stDeltaDR_fYmm", IsRequired = true)]
        public float stDeltaDRfYmm { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"stDeltaDR_fDeg", IsRequired = true)]
        public float stDeltaDRfDeg { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"stCompassData_nAHRS_Status", IsRequired = true)]
        public int stCompassDatanAHRSStatus { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"stCompassData_nAngleDeg10Times", IsRequired = true)]
        public int stCompassDatanAngleDeg10Times { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"stWheelData_Left_bWheelDriverFault", IsRequired = true)]
        public bool stWheelDataLeftbWheelDriverFault { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"stWheelData_Left_bWheelNotOper", IsRequired = true)]
        public bool stWheelDataLeftbWheelNotOper { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"stWheelData_Left_bWheelOverLoad", IsRequired = true)]
        public bool stWheelDataLeftbWheelOverLoad { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"stWheelData_Left_bWheelSelfTestError", IsRequired = true)]
        public bool stWheelDataLeftbWheelSelfTestError { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"stWheelData_Left_bWheelStuck", IsRequired = true)]
        public bool stWheelDataLeftbWheelStuck { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"stWheelData_Right_bWheelDriverFault", IsRequired = true)]
        public bool stWheelDataRightbWheelDriverFault { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"stWheelData_Right_bWheelNotOper", IsRequired = true)]
        public bool stWheelDataRightbWheelNotOper { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"stWheelData_Right_bWheelOverLoad", IsRequired = true)]
        public bool stWheelDataRightbWheelOverLoad { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"stWheelData_Right_bWheelSelfTestError", IsRequired = true)]
        public bool stWheelDataRightbWheelSelfTestError { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"stWheelData_Right_bWheelStuck", IsRequired = true)]
        public bool stWheelDataRightbWheelStuck { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"stUssData_Left", IsRequired = true)]
        public int stUssDataLeft { get; set; }

        [global::ProtoBuf.ProtoMember(21, Name = @"stUssData_Center", IsRequired = true)]
        public int stUssDataCenter { get; set; }

        [global::ProtoBuf.ProtoMember(22, Name = @"stUssData_Right", IsRequired = true)]
        public int stUssDataRight { get; set; }

        [global::ProtoBuf.ProtoMember(23, Name = @"stUssData_USS_OK", IsRequired = true)]
        public bool stUssDataUSSOK { get; set; }

        [global::ProtoBuf.ProtoMember(24, Name = @"stBumpData_isBumping", IsRequired = true)]
        public bool stBumpDataisBumping { get; set; }

        [global::ProtoBuf.ProtoMember(25, Name = @"stBumpData_No0", IsRequired = true)]
        public bool stBumpDataNo0 { get; set; }

        [global::ProtoBuf.ProtoMember(26, Name = @"stBumpData_No1", IsRequired = true)]
        public bool stBumpDataNo1 { get; set; }

        [global::ProtoBuf.ProtoMember(27, IsRequired = true)]
        public Uwb stUwbData { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
