// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: model_configuration.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ModelConfiguration : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time", IsRequired = true)]
        public Time Time { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"joint_names")]
        public global::System.Collections.Generic.List<string> JointNames { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(3, Name = @"joint_positions")]
        public double[] JointPositions { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"pose")]
        public Pose Pose { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"link_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LinkName
        {
            get { return __pbn__LinkName ?? ""; }
            set { __pbn__LinkName = value; }
        }
        public bool ShouldSerializeLinkName() => __pbn__LinkName != null;
        public void ResetLinkName() => __pbn__LinkName = null;
        private string __pbn__LinkName;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
