// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: model.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Model : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"is_static")]
        public bool IsStatic
        {
            get { return __pbn__IsStatic.GetValueOrDefault(); }
            set { __pbn__IsStatic = value; }
        }
        public bool ShouldSerializeIsStatic() => __pbn__IsStatic != null;
        public void ResetIsStatic() => __pbn__IsStatic = null;
        private bool? __pbn__IsStatic;

        [global::ProtoBuf.ProtoMember(4, Name = @"pose")]
        public Pose Pose { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"joint")]
        public global::System.Collections.Generic.List<Joint> Joints { get; } = new global::System.Collections.Generic.List<Joint>();

        [global::ProtoBuf.ProtoMember(6, Name = @"link")]
        public global::System.Collections.Generic.List<Link> Links { get; } = new global::System.Collections.Generic.List<Link>();

        [global::ProtoBuf.ProtoMember(7, Name = @"deleted")]
        public bool Deleted
        {
            get { return __pbn__Deleted.GetValueOrDefault(); }
            set { __pbn__Deleted = value; }
        }
        public bool ShouldSerializeDeleted() => __pbn__Deleted != null;
        public void ResetDeleted() => __pbn__Deleted = null;
        private bool? __pbn__Deleted;

        [global::ProtoBuf.ProtoMember(8, Name = @"visual")]
        public global::System.Collections.Generic.List<Visual> Visuals { get; } = new global::System.Collections.Generic.List<Visual>();

        [global::ProtoBuf.ProtoMember(9, Name = @"scale")]
        public Vector3d Scale { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"self_collide")]
        public bool SelfCollide
        {
            get { return __pbn__SelfCollide.GetValueOrDefault(); }
            set { __pbn__SelfCollide = value; }
        }
        public bool ShouldSerializeSelfCollide() => __pbn__SelfCollide != null;
        public void ResetSelfCollide() => __pbn__SelfCollide = null;
        private bool? __pbn__SelfCollide;

        [global::ProtoBuf.ProtoMember(11, Name = @"enable_wind")]
        public bool EnableWind
        {
            get { return __pbn__EnableWind.GetValueOrDefault(); }
            set { __pbn__EnableWind = value; }
        }
        public bool ShouldSerializeEnableWind() => __pbn__EnableWind != null;
        public void ResetEnableWind() => __pbn__EnableWind = null;
        private bool? __pbn__EnableWind;

        [global::ProtoBuf.ProtoMember(12, Name = @"model")]
        public global::System.Collections.Generic.List<Model> Models { get; } = new global::System.Collections.Generic.List<Model>();

        [global::ProtoBuf.ProtoMember(13, Name = @"plugin")]
        public global::System.Collections.Generic.List<Plugin> Plugins { get; } = new global::System.Collections.Generic.List<Plugin>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
