// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: path_info.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract(Name = @"Path_Info")]
    public partial class PathInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"datainfo", IsRequired = true)]
        public int Datainfo { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public float fXmm
        {
            get { return __pbn__fXmm.GetValueOrDefault(); }
            set { __pbn__fXmm = value; }
        }
        public bool ShouldSerializefXmm() => __pbn__fXmm != null;
        public void ResetfXmm() => __pbn__fXmm = null;
        private float? __pbn__fXmm;

        [global::ProtoBuf.ProtoMember(3)]
        public float fYmm
        {
            get { return __pbn__fYmm.GetValueOrDefault(); }
            set { __pbn__fYmm = value; }
        }
        public bool ShouldSerializefYmm() => __pbn__fYmm != null;
        public void ResetfYmm() => __pbn__fYmm = null;
        private float? __pbn__fYmm;

        [global::ProtoBuf.ProtoMember(4)]
        public float fDeg
        {
            get { return __pbn__fDeg.GetValueOrDefault(); }
            set { __pbn__fDeg = value; }
        }
        public bool ShouldSerializefDeg() => __pbn__fDeg != null;
        public void ResetfDeg() => __pbn__fDeg = null;
        private float? __pbn__fDeg;

        [global::ProtoBuf.ProtoMember(5, Name = @"corner")]
        public int Corner
        {
            get { return __pbn__Corner.GetValueOrDefault(); }
            set { __pbn__Corner = value; }
        }
        public bool ShouldSerializeCorner() => __pbn__Corner != null;
        public void ResetCorner() => __pbn__Corner = null;
        private int? __pbn__Corner;

        [global::ProtoBuf.ProtoMember(6, Name = @"index", IsRequired = true)]
        public int Index { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
