// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: physics.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Physics : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(Type.Ode)]
        public Type type
        {
            get { return __pbn__type ?? Type.Ode; }
            set { __pbn__type = value; }
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private Type? __pbn__type;

        [global::ProtoBuf.ProtoMember(2, Name = @"solver_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SolverType
        {
            get { return __pbn__SolverType ?? ""; }
            set { __pbn__SolverType = value; }
        }
        public bool ShouldSerializeSolverType() => __pbn__SolverType != null;
        public void ResetSolverType() => __pbn__SolverType = null;
        private string __pbn__SolverType;

        [global::ProtoBuf.ProtoMember(3, Name = @"min_step_size")]
        public double MinStepSize
        {
            get { return __pbn__MinStepSize.GetValueOrDefault(); }
            set { __pbn__MinStepSize = value; }
        }
        public bool ShouldSerializeMinStepSize() => __pbn__MinStepSize != null;
        public void ResetMinStepSize() => __pbn__MinStepSize = null;
        private double? __pbn__MinStepSize;

        [global::ProtoBuf.ProtoMember(4, Name = @"precon_iters")]
        public int PreconIters
        {
            get { return __pbn__PreconIters.GetValueOrDefault(); }
            set { __pbn__PreconIters = value; }
        }
        public bool ShouldSerializePreconIters() => __pbn__PreconIters != null;
        public void ResetPreconIters() => __pbn__PreconIters = null;
        private int? __pbn__PreconIters;

        [global::ProtoBuf.ProtoMember(5, Name = @"iters")]
        public int Iters
        {
            get { return __pbn__Iters.GetValueOrDefault(); }
            set { __pbn__Iters = value; }
        }
        public bool ShouldSerializeIters() => __pbn__Iters != null;
        public void ResetIters() => __pbn__Iters = null;
        private int? __pbn__Iters;

        [global::ProtoBuf.ProtoMember(6, Name = @"sor")]
        public double Sor
        {
            get { return __pbn__Sor.GetValueOrDefault(); }
            set { __pbn__Sor = value; }
        }
        public bool ShouldSerializeSor() => __pbn__Sor != null;
        public void ResetSor() => __pbn__Sor = null;
        private double? __pbn__Sor;

        [global::ProtoBuf.ProtoMember(7, Name = @"cfm")]
        public double Cfm
        {
            get { return __pbn__Cfm.GetValueOrDefault(); }
            set { __pbn__Cfm = value; }
        }
        public bool ShouldSerializeCfm() => __pbn__Cfm != null;
        public void ResetCfm() => __pbn__Cfm = null;
        private double? __pbn__Cfm;

        [global::ProtoBuf.ProtoMember(8, Name = @"erp")]
        public double Erp
        {
            get { return __pbn__Erp.GetValueOrDefault(); }
            set { __pbn__Erp = value; }
        }
        public bool ShouldSerializeErp() => __pbn__Erp != null;
        public void ResetErp() => __pbn__Erp = null;
        private double? __pbn__Erp;

        [global::ProtoBuf.ProtoMember(9, Name = @"contact_max_correcting_vel")]
        public double ContactMaxCorrectingVel
        {
            get { return __pbn__ContactMaxCorrectingVel.GetValueOrDefault(); }
            set { __pbn__ContactMaxCorrectingVel = value; }
        }
        public bool ShouldSerializeContactMaxCorrectingVel() => __pbn__ContactMaxCorrectingVel != null;
        public void ResetContactMaxCorrectingVel() => __pbn__ContactMaxCorrectingVel = null;
        private double? __pbn__ContactMaxCorrectingVel;

        [global::ProtoBuf.ProtoMember(10, Name = @"contact_surface_layer")]
        public double ContactSurfaceLayer
        {
            get { return __pbn__ContactSurfaceLayer.GetValueOrDefault(); }
            set { __pbn__ContactSurfaceLayer = value; }
        }
        public bool ShouldSerializeContactSurfaceLayer() => __pbn__ContactSurfaceLayer != null;
        public void ResetContactSurfaceLayer() => __pbn__ContactSurfaceLayer = null;
        private double? __pbn__ContactSurfaceLayer;

        [global::ProtoBuf.ProtoMember(11, Name = @"gravity")]
        public Vector3d Gravity { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"enable_physics")]
        public bool EnablePhysics
        {
            get { return __pbn__EnablePhysics.GetValueOrDefault(); }
            set { __pbn__EnablePhysics = value; }
        }
        public bool ShouldSerializeEnablePhysics() => __pbn__EnablePhysics != null;
        public void ResetEnablePhysics() => __pbn__EnablePhysics = null;
        private bool? __pbn__EnablePhysics;

        [global::ProtoBuf.ProtoMember(13, Name = @"real_time_factor")]
        public double RealTimeFactor
        {
            get { return __pbn__RealTimeFactor.GetValueOrDefault(); }
            set { __pbn__RealTimeFactor = value; }
        }
        public bool ShouldSerializeRealTimeFactor() => __pbn__RealTimeFactor != null;
        public void ResetRealTimeFactor() => __pbn__RealTimeFactor = null;
        private double? __pbn__RealTimeFactor;

        [global::ProtoBuf.ProtoMember(14, Name = @"real_time_update_rate")]
        public double RealTimeUpdateRate
        {
            get { return __pbn__RealTimeUpdateRate.GetValueOrDefault(); }
            set { __pbn__RealTimeUpdateRate = value; }
        }
        public bool ShouldSerializeRealTimeUpdateRate() => __pbn__RealTimeUpdateRate != null;
        public void ResetRealTimeUpdateRate() => __pbn__RealTimeUpdateRate = null;
        private double? __pbn__RealTimeUpdateRate;

        [global::ProtoBuf.ProtoMember(15, Name = @"max_step_size")]
        public double MaxStepSize
        {
            get { return __pbn__MaxStepSize.GetValueOrDefault(); }
            set { __pbn__MaxStepSize = value; }
        }
        public bool ShouldSerializeMaxStepSize() => __pbn__MaxStepSize != null;
        public void ResetMaxStepSize() => __pbn__MaxStepSize = null;
        private double? __pbn__MaxStepSize;

        [global::ProtoBuf.ProtoMember(16, Name = @"profile_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ProfileName
        {
            get { return __pbn__ProfileName ?? ""; }
            set { __pbn__ProfileName = value; }
        }
        public bool ShouldSerializeProfileName() => __pbn__ProfileName != null;
        public void ResetProfileName() => __pbn__ProfileName = null;
        private string __pbn__ProfileName;

        [global::ProtoBuf.ProtoMember(17, Name = @"magnetic_field")]
        public Vector3d MagneticField { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ODE")]
            Ode = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"BULLET")]
            Bullet = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SIMBODY")]
            Simbody = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"DART")]
            Dart = 4,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
