// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: pid.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract(Name = @"PID")]
    public partial class Pid : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"target")]
        [global::System.ComponentModel.DefaultValue(0)]
        public double Target
        {
            get { return __pbn__Target ?? 0; }
            set { __pbn__Target = value; }
        }
        public bool ShouldSerializeTarget() => __pbn__Target != null;
        public void ResetTarget() => __pbn__Target = null;
        private double? __pbn__Target;

        [global::ProtoBuf.ProtoMember(2, Name = @"p_gain")]
        [global::System.ComponentModel.DefaultValue(0)]
        public double PGain
        {
            get { return __pbn__PGain ?? 0; }
            set { __pbn__PGain = value; }
        }
        public bool ShouldSerializePGain() => __pbn__PGain != null;
        public void ResetPGain() => __pbn__PGain = null;
        private double? __pbn__PGain;

        [global::ProtoBuf.ProtoMember(3, Name = @"i_gain")]
        [global::System.ComponentModel.DefaultValue(0)]
        public double IGain
        {
            get { return __pbn__IGain ?? 0; }
            set { __pbn__IGain = value; }
        }
        public bool ShouldSerializeIGain() => __pbn__IGain != null;
        public void ResetIGain() => __pbn__IGain = null;
        private double? __pbn__IGain;

        [global::ProtoBuf.ProtoMember(4, Name = @"d_gain")]
        [global::System.ComponentModel.DefaultValue(0)]
        public double DGain
        {
            get { return __pbn__DGain ?? 0; }
            set { __pbn__DGain = value; }
        }
        public bool ShouldSerializeDGain() => __pbn__DGain != null;
        public void ResetDGain() => __pbn__DGain = null;
        private double? __pbn__DGain;

        [global::ProtoBuf.ProtoMember(5, Name = @"i_max")]
        [global::System.ComponentModel.DefaultValue(0)]
        public double IMax
        {
            get { return __pbn__IMax ?? 0; }
            set { __pbn__IMax = value; }
        }
        public bool ShouldSerializeIMax() => __pbn__IMax != null;
        public void ResetIMax() => __pbn__IMax = null;
        private double? __pbn__IMax;

        [global::ProtoBuf.ProtoMember(6, Name = @"i_min")]
        [global::System.ComponentModel.DefaultValue(0)]
        public double IMin
        {
            get { return __pbn__IMin ?? 0; }
            set { __pbn__IMin = value; }
        }
        public bool ShouldSerializeIMin() => __pbn__IMin != null;
        public void ResetIMin() => __pbn__IMin = null;
        private double? __pbn__IMin;

        [global::ProtoBuf.ProtoMember(7, Name = @"limit")]
        [global::System.ComponentModel.DefaultValue(0)]
        public double Limit
        {
            get { return __pbn__Limit ?? 0; }
            set { __pbn__Limit = value; }
        }
        public bool ShouldSerializeLimit() => __pbn__Limit != null;
        public void ResetLimit() => __pbn__Limit = null;
        private double? __pbn__Limit;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
