// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: planegeom.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PlaneGeom : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"normal", IsRequired = true)]
        public Vector3d Normal { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"size", IsRequired = true)]
        public Vector2d Size { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"d")]
        [global::System.ComponentModel.DefaultValue(0)]
        public double D
        {
            get { return __pbn__D ?? 0; }
            set { __pbn__D = value; }
        }
        public bool ShouldSerializeD() => __pbn__D != null;
        public void ResetD() => __pbn__D = null;
        private double? __pbn__D;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
