// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: pose_animation.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PoseAnimation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"model_name", IsRequired = true)]
        public string ModelName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"model_id")]
        public uint ModelId
        {
            get { return __pbn__ModelId.GetValueOrDefault(); }
            set { __pbn__ModelId = value; }
        }
        public bool ShouldSerializeModelId() => __pbn__ModelId != null;
        public void ResetModelId() => __pbn__ModelId = null;
        private uint? __pbn__ModelId;

        [global::ProtoBuf.ProtoMember(3, Name = @"pose")]
        public global::System.Collections.Generic.List<Pose> Poses { get; } = new global::System.Collections.Generic.List<Pose>();

        [global::ProtoBuf.ProtoMember(4, Name = @"time")]
        public global::System.Collections.Generic.List<Time> Times { get; } = new global::System.Collections.Generic.List<Time>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
