// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: projector.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Projector : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"texture")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Texture
        {
            get { return __pbn__Texture ?? ""; }
            set { __pbn__Texture = value; }
        }
        public bool ShouldSerializeTexture() => __pbn__Texture != null;
        public void ResetTexture() => __pbn__Texture = null;
        private string __pbn__Texture;

        [global::ProtoBuf.ProtoMember(3, Name = @"pose")]
        public Pose Pose { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"fov")]
        [global::System.ComponentModel.DefaultValue(0.785)]
        public double Fov
        {
            get { return __pbn__Fov ?? 0.785; }
            set { __pbn__Fov = value; }
        }
        public bool ShouldSerializeFov() => __pbn__Fov != null;
        public void ResetFov() => __pbn__Fov = null;
        private double? __pbn__Fov;

        [global::ProtoBuf.ProtoMember(5, Name = @"near_clip")]
        [global::System.ComponentModel.DefaultValue(0.1)]
        public double NearClip
        {
            get { return __pbn__NearClip ?? 0.1; }
            set { __pbn__NearClip = value; }
        }
        public bool ShouldSerializeNearClip() => __pbn__NearClip != null;
        public void ResetNearClip() => __pbn__NearClip = null;
        private double? __pbn__NearClip;

        [global::ProtoBuf.ProtoMember(6, Name = @"far_clip")]
        [global::System.ComponentModel.DefaultValue(10)]
        public double FarClip
        {
            get { return __pbn__FarClip ?? 10; }
            set { __pbn__FarClip = value; }
        }
        public bool ShouldSerializeFarClip() => __pbn__FarClip != null;
        public void ResetFarClip() => __pbn__FarClip = null;
        private double? __pbn__FarClip;

        [global::ProtoBuf.ProtoMember(7, Name = @"enabled")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool Enabled
        {
            get { return __pbn__Enabled ?? true; }
            set { __pbn__Enabled = value; }
        }
        public bool ShouldSerializeEnabled() => __pbn__Enabled != null;
        public void ResetEnabled() => __pbn__Enabled = null;
        private bool? __pbn__Enabled;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
