// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: publish.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Publish : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"topic", IsRequired = true)]
        public string Topic { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"msg_type", IsRequired = true)]
        public string MsgType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"host", IsRequired = true)]
        public string Host { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"port", IsRequired = true)]
        public uint Port { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
