// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: request.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Request : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string request { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"data")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Data
        {
            get { return __pbn__Data ?? ""; }
            set { __pbn__Data = value; }
        }
        public bool ShouldSerializeData() => __pbn__Data != null;
        public void ResetData() => __pbn__Data = null;
        private string __pbn__Data;

        [global::ProtoBuf.ProtoMember(4, Name = @"dbl_data")]
        public double DblData
        {
            get { return __pbn__DblData.GetValueOrDefault(); }
            set { __pbn__DblData = value; }
        }
        public bool ShouldSerializeDblData() => __pbn__DblData != null;
        public void ResetDblData() => __pbn__DblData = null;
        private double? __pbn__DblData;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
