// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: rest_login.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RestLogin : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"url", IsRequired = true)]
        public string Url { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"username")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Username
        {
            get { return __pbn__Username ?? ""; }
            set { __pbn__Username = value; }
        }
        public bool ShouldSerializeUsername() => __pbn__Username != null;
        public void ResetUsername() => __pbn__Username = null;
        private string __pbn__Username;

        [global::ProtoBuf.ProtoMember(4, Name = @"password")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password
        {
            get { return __pbn__Password ?? ""; }
            set { __pbn__Password = value; }
        }
        public bool ShouldSerializePassword() => __pbn__Password != null;
        public void ResetPassword() => __pbn__Password = null;
        private string __pbn__Password;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
