// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: rest_response.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RestResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public Type type { get; set; } = Type.Success;

        [global::ProtoBuf.ProtoMember(3, Name = @"msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Msg
        {
            get { return __pbn__Msg ?? ""; }
            set { __pbn__Msg = value; }
        }
        public bool ShouldSerializeMsg() => __pbn__Msg != null;
        public void ResetMsg() => __pbn__Msg = null;
        private string __pbn__Msg;

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SUCCESS")]
            Success = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ERR")]
            Err = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"LOGIN")]
            Login = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"LOGOUT")]
            Logout = 4,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
