// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: robot_path.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract(Name = @"Robot_Path")]
    public partial class RobotPath : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"datasize", IsRequired = true)]
        public int Datasize { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"fXmm")]
        public float[] fXmms { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"fYmm")]
        public float[] fYmms { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"fDeg")]
        public float[] fDegs { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"corner")]
        public int[] Corners { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
