// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: scene.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Scene : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ambient")]
        public Color Ambient { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"background")]
        public Color Background { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"sky")]
        public Sky Sky { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"shadows")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool Shadows
        {
            get { return __pbn__Shadows ?? true; }
            set { __pbn__Shadows = value; }
        }
        public bool ShouldSerializeShadows() => __pbn__Shadows != null;
        public void ResetShadows() => __pbn__Shadows = null;
        private bool? __pbn__Shadows;

        [global::ProtoBuf.ProtoMember(6, Name = @"fog")]
        public Fog Fog { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"grid")]
        public bool Grid
        {
            get { return __pbn__Grid.GetValueOrDefault(); }
            set { __pbn__Grid = value; }
        }
        public bool ShouldSerializeGrid() => __pbn__Grid != null;
        public void ResetGrid() => __pbn__Grid = null;
        private bool? __pbn__Grid;

        [global::ProtoBuf.ProtoMember(8, Name = @"model")]
        public global::System.Collections.Generic.List<Model> Models { get; } = new global::System.Collections.Generic.List<Model>();

        [global::ProtoBuf.ProtoMember(9, Name = @"light")]
        public global::System.Collections.Generic.List<Light> Lights { get; } = new global::System.Collections.Generic.List<Light>();

        [global::ProtoBuf.ProtoMember(10, Name = @"joint")]
        public global::System.Collections.Generic.List<Joint> Joints { get; } = new global::System.Collections.Generic.List<Joint>();

        [global::ProtoBuf.ProtoMember(11, Name = @"origin_visual")]
        public bool OriginVisual
        {
            get { return __pbn__OriginVisual.GetValueOrDefault(); }
            set { __pbn__OriginVisual = value; }
        }
        public bool ShouldSerializeOriginVisual() => __pbn__OriginVisual != null;
        public void ResetOriginVisual() => __pbn__OriginVisual = null;
        private bool? __pbn__OriginVisual;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
