// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: sensor.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Sensor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"parent", IsRequired = true)]
        public string Parent { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"parent_id")]
        public uint ParentId
        {
            get { return __pbn__ParentId.GetValueOrDefault(); }
            set { __pbn__ParentId = value; }
        }
        public bool ShouldSerializeParentId() => __pbn__ParentId != null;
        public void ResetParentId() => __pbn__ParentId = null;
        private uint? __pbn__ParentId;

        [global::ProtoBuf.ProtoMember(5, Name = @"type", IsRequired = true)]
        public string Type { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"always_on")]
        public bool AlwaysOn
        {
            get { return __pbn__AlwaysOn.GetValueOrDefault(); }
            set { __pbn__AlwaysOn = value; }
        }
        public bool ShouldSerializeAlwaysOn() => __pbn__AlwaysOn != null;
        public void ResetAlwaysOn() => __pbn__AlwaysOn = null;
        private bool? __pbn__AlwaysOn;

        [global::ProtoBuf.ProtoMember(7, Name = @"update_rate")]
        public double UpdateRate
        {
            get { return __pbn__UpdateRate.GetValueOrDefault(); }
            set { __pbn__UpdateRate = value; }
        }
        public bool ShouldSerializeUpdateRate() => __pbn__UpdateRate != null;
        public void ResetUpdateRate() => __pbn__UpdateRate = null;
        private double? __pbn__UpdateRate;

        [global::ProtoBuf.ProtoMember(8, Name = @"pose")]
        public Pose Pose { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"camera")]
        public CameraSensor Camera { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"ray")]
        public RaySensor Ray { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"contact")]
        public ContactSensor Contact { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"visualize")]
        public bool Visualize
        {
            get { return __pbn__Visualize.GetValueOrDefault(); }
            set { __pbn__Visualize = value; }
        }
        public bool ShouldSerializeVisualize() => __pbn__Visualize != null;
        public void ResetVisualize() => __pbn__Visualize = null;
        private bool? __pbn__Visualize;

        [global::ProtoBuf.ProtoMember(13, Name = @"topic")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Topic
        {
            get { return __pbn__Topic ?? ""; }
            set { __pbn__Topic = value; }
        }
        public bool ShouldSerializeTopic() => __pbn__Topic != null;
        public void ResetTopic() => __pbn__Topic = null;
        private string __pbn__Topic;

        [global::ProtoBuf.ProtoMember(14, Name = @"logical_camera")]
        public LogicalCameraSensor LogicalCamera { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"gps")]
        public GPSSensor Gps { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"imu")]
        public IMUSensor Imu { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
