// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: sensor_noise.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SensorNoise : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public Type type { get; set; } = Type.None;

        [global::ProtoBuf.ProtoMember(2, Name = @"mean")]
        public double Mean
        {
            get => __pbn__Mean.GetValueOrDefault();
            set => __pbn__Mean = value;
        }
        public bool ShouldSerializeMean() => __pbn__Mean != null;
        public void ResetMean() => __pbn__Mean = null;
        private double? __pbn__Mean;

        [global::ProtoBuf.ProtoMember(3, Name = @"stddev")]
        public double Stddev
        {
            get => __pbn__Stddev.GetValueOrDefault();
            set => __pbn__Stddev = value;
        }
        public bool ShouldSerializeStddev() => __pbn__Stddev != null;
        public void ResetStddev() => __pbn__Stddev = null;
        private double? __pbn__Stddev;

        [global::ProtoBuf.ProtoMember(4, Name = @"bias_mean")]
        public double BiasMean
        {
            get => __pbn__BiasMean.GetValueOrDefault();
            set => __pbn__BiasMean = value;
        }
        public bool ShouldSerializeBiasMean() => __pbn__BiasMean != null;
        public void ResetBiasMean() => __pbn__BiasMean = null;
        private double? __pbn__BiasMean;

        [global::ProtoBuf.ProtoMember(5, Name = @"bias_stddev")]
        public double BiasStddev
        {
            get => __pbn__BiasStddev.GetValueOrDefault();
            set => __pbn__BiasStddev = value;
        }
        public bool ShouldSerializeBiasStddev() => __pbn__BiasStddev != null;
        public void ResetBiasStddev() => __pbn__BiasStddev = null;
        private double? __pbn__BiasStddev;

        [global::ProtoBuf.ProtoMember(6, Name = @"precision")]
        public double Precision
        {
            get => __pbn__Precision.GetValueOrDefault();
            set => __pbn__Precision = value;
        }
        public bool ShouldSerializePrecision() => __pbn__Precision != null;
        public void ResetPrecision() => __pbn__Precision = null;
        private double? __pbn__Precision;

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
            None = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"GAUSSIAN")]
            Gaussian = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"GAUSSIAN_QUANTIZED")]
            GaussianQuantized = 3,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
