// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: shadows.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Shadows : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(5, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(ShadowType.StencilAdditive)]
        public ShadowType Type
        {
            get { return __pbn__Type ?? ShadowType.StencilAdditive; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private ShadowType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(6, Name = @"color")]
        public Color Color { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ShadowType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"STENCIL_ADDITIVE")]
            StencilAdditive = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"STENCIL_MODULATIVE")]
            StencilModulative = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"TEXTURE_ADDITIVE")]
            TextureAdditive = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TEXTURE_MODULATIVE")]
            TextureModulative = 4,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
