// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: sky.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Sky : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"time")]
        public double Time
        {
            get { return __pbn__Time.GetValueOrDefault(); }
            set { __pbn__Time = value; }
        }
        public bool ShouldSerializeTime() => __pbn__Time != null;
        public void ResetTime() => __pbn__Time = null;
        private double? __pbn__Time;

        [global::ProtoBuf.ProtoMember(2, Name = @"sunrise")]
        public double Sunrise
        {
            get { return __pbn__Sunrise.GetValueOrDefault(); }
            set { __pbn__Sunrise = value; }
        }
        public bool ShouldSerializeSunrise() => __pbn__Sunrise != null;
        public void ResetSunrise() => __pbn__Sunrise = null;
        private double? __pbn__Sunrise;

        [global::ProtoBuf.ProtoMember(3, Name = @"sunset")]
        public double Sunset
        {
            get { return __pbn__Sunset.GetValueOrDefault(); }
            set { __pbn__Sunset = value; }
        }
        public bool ShouldSerializeSunset() => __pbn__Sunset != null;
        public void ResetSunset() => __pbn__Sunset = null;
        private double? __pbn__Sunset;

        [global::ProtoBuf.ProtoMember(4, Name = @"wind_speed")]
        public double WindSpeed
        {
            get { return __pbn__WindSpeed.GetValueOrDefault(); }
            set { __pbn__WindSpeed = value; }
        }
        public bool ShouldSerializeWindSpeed() => __pbn__WindSpeed != null;
        public void ResetWindSpeed() => __pbn__WindSpeed = null;
        private double? __pbn__WindSpeed;

        [global::ProtoBuf.ProtoMember(5, Name = @"wind_direction")]
        public double WindDirection
        {
            get { return __pbn__WindDirection.GetValueOrDefault(); }
            set { __pbn__WindDirection = value; }
        }
        public bool ShouldSerializeWindDirection() => __pbn__WindDirection != null;
        public void ResetWindDirection() => __pbn__WindDirection = null;
        private double? __pbn__WindDirection;

        [global::ProtoBuf.ProtoMember(6, Name = @"cloud_ambient")]
        public Color CloudAmbient { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"humidity")]
        public double Humidity
        {
            get { return __pbn__Humidity.GetValueOrDefault(); }
            set { __pbn__Humidity = value; }
        }
        public bool ShouldSerializeHumidity() => __pbn__Humidity != null;
        public void ResetHumidity() => __pbn__Humidity = null;
        private double? __pbn__Humidity;

        [global::ProtoBuf.ProtoMember(8, Name = @"mean_cloud_size")]
        public double MeanCloudSize
        {
            get { return __pbn__MeanCloudSize.GetValueOrDefault(); }
            set { __pbn__MeanCloudSize = value; }
        }
        public bool ShouldSerializeMeanCloudSize() => __pbn__MeanCloudSize != null;
        public void ResetMeanCloudSize() => __pbn__MeanCloudSize = null;
        private double? __pbn__MeanCloudSize;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
