// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: sonar.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace cloisim.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Sonar : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"frame", IsRequired = true)]
        public string Frame { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"world_pose", IsRequired = true)]
        public Pose WorldPose { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"range_min", IsRequired = true)]
        public double RangeMin { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"range_max", IsRequired = true)]
        public double RangeMax { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"radius", IsRequired = true)]
        public double Radius { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"range", IsRequired = true)]
        public double Range { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"contact")]
        public Vector3d Contact { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
