// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: spherical_coordinates.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SphericalCoordinates : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public SurfaceModel surface_model { get; set; } = SurfaceModel.EarthWgs84;

        [global::ProtoBuf.ProtoMember(2, Name = @"latitude_deg", IsRequired = true)]
        public double LatitudeDeg { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"longitude_deg", IsRequired = true)]
        public double LongitudeDeg { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"elevation", IsRequired = true)]
        public double Elevation { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"heading_deg", IsRequired = true)]
        public double HeadingDeg { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum SurfaceModel
        {
            [global::ProtoBuf.ProtoEnum(Name = @"EARTH_WGS84")]
            EarthWgs84 = 1,
        }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
