// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: topic_info.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TopicInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"msg_type", IsRequired = true)]
        public string MsgType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"publisher")]
        public global::System.Collections.Generic.List<Publish> Publishers { get; } = new global::System.Collections.Generic.List<Publish>();

        [global::ProtoBuf.ProtoMember(3, Name = @"subscriber")]
        public global::System.Collections.Generic.List<Subscribe> Subscribers { get; } = new global::System.Collections.Generic.List<Subscribe>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
