// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: track_visual.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TrackVisual : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"id")]
        public uint Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(3, Name = @"inherit_orientation")]
        public bool InheritOrientation
        {
            get { return __pbn__InheritOrientation.GetValueOrDefault(); }
            set { __pbn__InheritOrientation = value; }
        }
        public bool ShouldSerializeInheritOrientation() => __pbn__InheritOrientation != null;
        public void ResetInheritOrientation() => __pbn__InheritOrientation = null;
        private bool? __pbn__InheritOrientation;

        [global::ProtoBuf.ProtoMember(4, Name = @"min_dist")]
        public double MinDist
        {
            get { return __pbn__MinDist.GetValueOrDefault(); }
            set { __pbn__MinDist = value; }
        }
        public bool ShouldSerializeMinDist() => __pbn__MinDist != null;
        public void ResetMinDist() => __pbn__MinDist = null;
        private double? __pbn__MinDist;

        [global::ProtoBuf.ProtoMember(5, Name = @"max_dist")]
        public double MaxDist
        {
            get { return __pbn__MaxDist.GetValueOrDefault(); }
            set { __pbn__MaxDist = value; }
        }
        public bool ShouldSerializeMaxDist() => __pbn__MaxDist != null;
        public void ResetMaxDist() => __pbn__MaxDist = null;
        private double? __pbn__MaxDist;

        [global::ProtoBuf.ProtoMember(6, Name = @"static")]
        public bool Static
        {
            get { return __pbn__Static.GetValueOrDefault(); }
            set { __pbn__Static = value; }
        }
        public bool ShouldSerializeStatic() => __pbn__Static != null;
        public void ResetStatic() => __pbn__Static = null;
        private bool? __pbn__Static;

        [global::ProtoBuf.ProtoMember(7, Name = @"use_model_frame")]
        public bool UseModelFrame
        {
            get { return __pbn__UseModelFrame.GetValueOrDefault(); }
            set { __pbn__UseModelFrame = value; }
        }
        public bool ShouldSerializeUseModelFrame() => __pbn__UseModelFrame != null;
        public void ResetUseModelFrame() => __pbn__UseModelFrame = null;
        private bool? __pbn__UseModelFrame;

        [global::ProtoBuf.ProtoMember(8, Name = @"xyz")]
        public Vector3d Xyz { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"inherit_yaw")]
        public bool InheritYaw
        {
            get { return __pbn__InheritYaw.GetValueOrDefault(); }
            set { __pbn__InheritYaw = value; }
        }
        public bool ShouldSerializeInheritYaw() => __pbn__InheritYaw != null;
        public void ResetInheritYaw() => __pbn__InheritYaw = null;
        private bool? __pbn__InheritYaw;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
