// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: user_cmd_stats.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class UserCmdStats : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"undo_cmd_count", IsRequired = true)]
        public uint UndoCmdCount { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"redo_cmd_count", IsRequired = true)]
        public uint RedoCmdCount { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"undo_cmd")]
        public global::System.Collections.Generic.List<UserCmd> UndoCmds { get; } = new global::System.Collections.Generic.List<UserCmd>();

        [global::ProtoBuf.ProtoMember(4, Name = @"redo_cmd")]
        public global::System.Collections.Generic.List<UserCmd> RedoCmds { get; } = new global::System.Collections.Generic.List<UserCmd>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
