// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: uwb.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Uwb : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pos", IsRequired = true)]
        public Vector3d Pos { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"err", IsRequired = true)]
        public int Err { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"reserved")]
        public int Reserved
        {
            get { return __pbn__Reserved.GetValueOrDefault(); }
            set { __pbn__Reserved = value; }
        }
        public bool ShouldSerializeReserved() => __pbn__Reserved != null;
        public void ResetReserved() => __pbn__Reserved = null;
        private int? __pbn__Reserved;

        [global::ProtoBuf.ProtoMember(4, Name = @"anchor")]
        public global::System.Collections.Generic.List<UwbAnchor> Anchors { get; } = new global::System.Collections.Generic.List<UwbAnchor>();

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
