// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: world_modify.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WorldModify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"world_name", IsRequired = true)]
        public string WorldName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"remove")]
        public bool Remove
        {
            get { return __pbn__Remove.GetValueOrDefault(); }
            set { __pbn__Remove = value; }
        }
        public bool ShouldSerializeRemove() => __pbn__Remove != null;
        public void ResetRemove() => __pbn__Remove = null;
        private bool? __pbn__Remove;

        [global::ProtoBuf.ProtoMember(3, Name = @"create")]
        public bool Create
        {
            get { return __pbn__Create.GetValueOrDefault(); }
            set { __pbn__Create = value; }
        }
        public bool ShouldSerializeCreate() => __pbn__Create != null;
        public void ResetCreate() => __pbn__Create = null;
        private bool? __pbn__Create;

        [global::ProtoBuf.ProtoMember(4, Name = @"cloned")]
        public bool Cloned
        {
            get { return __pbn__Cloned.GetValueOrDefault(); }
            set { __pbn__Cloned = value; }
        }
        public bool ShouldSerializeCloned() => __pbn__Cloned != null;
        public void ResetCloned() => __pbn__Cloned = null;
        private bool? __pbn__Cloned;

        [global::ProtoBuf.ProtoMember(5, Name = @"cloned_uri")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ClonedUri
        {
            get { return __pbn__ClonedUri ?? ""; }
            set { __pbn__ClonedUri = value; }
        }
        public bool ShouldSerializeClonedUri() => __pbn__ClonedUri != null;
        public void ResetClonedUri() => __pbn__ClonedUri = null;
        private string __pbn__ClonedUri;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
