// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: world_control.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WorldControl : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"pause")]
        public bool Pause
        {
            get { return __pbn__Pause.GetValueOrDefault(); }
            set { __pbn__Pause = value; }
        }
        public bool ShouldSerializePause() => __pbn__Pause != null;
        public void ResetPause() => __pbn__Pause = null;
        private bool? __pbn__Pause;

        [global::ProtoBuf.ProtoMember(2, Name = @"step")]
        public bool Step
        {
            get { return __pbn__Step.GetValueOrDefault(); }
            set { __pbn__Step = value; }
        }
        public bool ShouldSerializeStep() => __pbn__Step != null;
        public void ResetStep() => __pbn__Step = null;
        private bool? __pbn__Step;

        [global::ProtoBuf.ProtoMember(3, Name = @"multi_step")]
        public uint MultiStep
        {
            get { return __pbn__MultiStep.GetValueOrDefault(); }
            set { __pbn__MultiStep = value; }
        }
        public bool ShouldSerializeMultiStep() => __pbn__MultiStep != null;
        public void ResetMultiStep() => __pbn__MultiStep = null;
        private uint? __pbn__MultiStep;

        [global::ProtoBuf.ProtoMember(4, Name = @"reset")]
        public WorldReset Reset { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"seed")]
        public uint Seed
        {
            get { return __pbn__Seed.GetValueOrDefault(); }
            set { __pbn__Seed = value; }
        }
        public bool ShouldSerializeSeed() => __pbn__Seed != null;
        public void ResetSeed() => __pbn__Seed = null;
        private uint? __pbn__Seed;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
