// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: world_reset.proto
// </auto-generated>

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace gazebo.msgs
{

    [global::ProtoBuf.ProtoContract()]
    public partial class WorldReset : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"all")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool All
        {
            get { return __pbn__All ?? true; }
            set { __pbn__All = value; }
        }
        public bool ShouldSerializeAll() => __pbn__All != null;
        public void ResetAll() => __pbn__All = null;
        private bool? __pbn__All;

        [global::ProtoBuf.ProtoMember(2, Name = @"time_only")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool TimeOnly
        {
            get { return __pbn__TimeOnly ?? false; }
            set { __pbn__TimeOnly = value; }
        }
        public bool ShouldSerializeTimeOnly() => __pbn__TimeOnly != null;
        public void ResetTimeOnly() => __pbn__TimeOnly = null;
        private bool? __pbn__TimeOnly;

        [global::ProtoBuf.ProtoMember(3, Name = @"model_only")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool ModelOnly
        {
            get { return __pbn__ModelOnly ?? false; }
            set { __pbn__ModelOnly = value; }
        }
        public bool ShouldSerializeModelOnly() => __pbn__ModelOnly != null;
        public void ResetModelOnly() => __pbn__ModelOnly = null;
        private bool? __pbn__ModelOnly;

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
